package com.sforce.soap.enterprise.sobject;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class DatacloudContact extends com.sforce.soap.enterprise.sobject.SObject {

    /**
     * Constructor
     */
    public DatacloudContact() {}

    /**
     * element : City of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo City__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","City","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean City__is_set = false;

    private java.lang.String City;

    public java.lang.String getCity() {
      return City;
    }

    public void setCity(java.lang.String City) {
      this.City = City;
      City__is_set = true;
    }

    /**
     * element : CompanyId of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo CompanyId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CompanyId","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean CompanyId__is_set = false;

    private java.lang.String CompanyId;

    public java.lang.String getCompanyId() {
      return CompanyId;
    }

    public void setCompanyId(java.lang.String CompanyId) {
      this.CompanyId = CompanyId;
      CompanyId__is_set = true;
    }

    /**
     * element : CompanyName of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo CompanyName__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CompanyName","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean CompanyName__is_set = false;

    private java.lang.String CompanyName;

    public java.lang.String getCompanyName() {
      return CompanyName;
    }

    public void setCompanyName(java.lang.String CompanyName) {
      this.CompanyName = CompanyName;
      CompanyName__is_set = true;
    }

    /**
     * element : ContactId of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ContactId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ContactId","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean ContactId__is_set = false;

    private java.lang.String ContactId;

    public java.lang.String getContactId() {
      return ContactId;
    }

    public void setContactId(java.lang.String ContactId) {
      this.ContactId = ContactId;
      ContactId__is_set = true;
    }

    /**
     * element : Country of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Country__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Country","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Country__is_set = false;

    private java.lang.String Country;

    public java.lang.String getCountry() {
      return Country;
    }

    public void setCountry(java.lang.String Country) {
      this.Country = Country;
      Country__is_set = true;
    }

    /**
     * element : Department of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Department__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Department","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Department__is_set = false;

    private java.lang.String Department;

    public java.lang.String getDepartment() {
      return Department;
    }

    public void setDepartment(java.lang.String Department) {
      this.Department = Department;
      Department__is_set = true;
    }

    /**
     * element : Email of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Email__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Email","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Email__is_set = false;

    private java.lang.String Email;

    public java.lang.String getEmail() {
      return Email;
    }

    public void setEmail(java.lang.String Email) {
      this.Email = Email;
      Email__is_set = true;
    }

    /**
     * element : ExternalId of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ExternalId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ExternalId","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean ExternalId__is_set = false;

    private java.lang.String ExternalId;

    public java.lang.String getExternalId() {
      return ExternalId;
    }

    public void setExternalId(java.lang.String ExternalId) {
      this.ExternalId = ExternalId;
      ExternalId__is_set = true;
    }

    /**
     * element : FirstName of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo FirstName__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","FirstName","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean FirstName__is_set = false;

    private java.lang.String FirstName;

    public java.lang.String getFirstName() {
      return FirstName;
    }

    public void setFirstName(java.lang.String FirstName) {
      this.FirstName = FirstName;
      FirstName__is_set = true;
    }

    /**
     * element : IsInactive of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo IsInactive__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","IsInactive","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean IsInactive__is_set = false;

    private java.lang.Boolean IsInactive;

    public java.lang.Boolean getIsInactive() {
      return IsInactive;
    }

    public void setIsInactive(java.lang.Boolean IsInactive) {
      this.IsInactive = IsInactive;
      IsInactive__is_set = true;
    }

    /**
     * element : IsOwned of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo IsOwned__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","IsOwned","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean IsOwned__is_set = false;

    private java.lang.Boolean IsOwned;

    public java.lang.Boolean getIsOwned() {
      return IsOwned;
    }

    public void setIsOwned(java.lang.Boolean IsOwned) {
      this.IsOwned = IsOwned;
      IsOwned__is_set = true;
    }

    /**
     * element : LastName of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo LastName__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","LastName","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean LastName__is_set = false;

    private java.lang.String LastName;

    public java.lang.String getLastName() {
      return LastName;
    }

    public void setLastName(java.lang.String LastName) {
      this.LastName = LastName;
      LastName__is_set = true;
    }

    /**
     * element : Level of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Level__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Level","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Level__is_set = false;

    private java.lang.String Level;

    public java.lang.String getLevel() {
      return Level;
    }

    public void setLevel(java.lang.String Level) {
      this.Level = Level;
      Level__is_set = true;
    }

    /**
     * element : Phone of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Phone__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Phone","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Phone__is_set = false;

    private java.lang.String Phone;

    public java.lang.String getPhone() {
      return Phone;
    }

    public void setPhone(java.lang.String Phone) {
      this.Phone = Phone;
      Phone__is_set = true;
    }

    /**
     * element : SocialHandles of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo SocialHandles__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","SocialHandles","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean SocialHandles__is_set = false;

    private com.sforce.soap.enterprise.QueryResult SocialHandles;

    public com.sforce.soap.enterprise.QueryResult getSocialHandles() {
      return SocialHandles;
    }

    public void setSocialHandles(com.sforce.soap.enterprise.QueryResult SocialHandles) {
      this.SocialHandles = SocialHandles;
      SocialHandles__is_set = true;
    }

    /**
     * element : State of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo State__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","State","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean State__is_set = false;

    private java.lang.String State;

    public java.lang.String getState() {
      return State;
    }

    public void setState(java.lang.String State) {
      this.State = State;
      State__is_set = true;
    }

    /**
     * element : Street of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Street__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Street","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Street__is_set = false;

    private java.lang.String Street;

    public java.lang.String getStreet() {
      return Street;
    }

    public void setStreet(java.lang.String Street) {
      this.Street = Street;
      Street__is_set = true;
    }

    /**
     * element : Title of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Title__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Title","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Title__is_set = false;

    private java.lang.String Title;

    public java.lang.String getTitle() {
      return Title;
    }

    public void setTitle(java.lang.String Title) {
      this.Title = Title;
      Title__is_set = true;
    }

    /**
     * element : UpdatedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo UpdatedDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","UpdatedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean UpdatedDate__is_set = false;

    private java.util.Calendar UpdatedDate;

    public java.util.Calendar getUpdatedDate() {
      return UpdatedDate;
    }

    public void setUpdatedDate(java.util.Calendar UpdatedDate) {
      this.UpdatedDate = UpdatedDate;
      UpdatedDate__is_set = true;
    }

    /**
     * element : Zip of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Zip__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Zip","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Zip__is_set = false;

    private java.lang.String Zip;

    public java.lang.String getZip() {
      return Zip;
    }

    public void setZip(java.lang.String Zip) {
      this.Zip = Zip;
      Zip__is_set = true;
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      __typeMapper.writeXsiType(__out, "urn:sobject.enterprise.soap.sforce.com", "DatacloudContact");
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       super.writeFields(__out, __typeMapper);
       __typeMapper.writeString(__out, City__typeInfo, City, City__is_set);
       __typeMapper.writeString(__out, CompanyId__typeInfo, CompanyId, CompanyId__is_set);
       __typeMapper.writeString(__out, CompanyName__typeInfo, CompanyName, CompanyName__is_set);
       __typeMapper.writeString(__out, ContactId__typeInfo, ContactId, ContactId__is_set);
       __typeMapper.writeString(__out, Country__typeInfo, Country, Country__is_set);
       __typeMapper.writeString(__out, Department__typeInfo, Department, Department__is_set);
       __typeMapper.writeString(__out, Email__typeInfo, Email, Email__is_set);
       __typeMapper.writeString(__out, ExternalId__typeInfo, ExternalId, ExternalId__is_set);
       __typeMapper.writeString(__out, FirstName__typeInfo, FirstName, FirstName__is_set);
       __typeMapper.writeObject(__out, IsInactive__typeInfo, IsInactive, IsInactive__is_set);
       __typeMapper.writeObject(__out, IsOwned__typeInfo, IsOwned, IsOwned__is_set);
       __typeMapper.writeString(__out, LastName__typeInfo, LastName, LastName__is_set);
       __typeMapper.writeString(__out, Level__typeInfo, Level, Level__is_set);
       __typeMapper.writeString(__out, Phone__typeInfo, Phone, Phone__is_set);
       __typeMapper.writeObject(__out, SocialHandles__typeInfo, SocialHandles, SocialHandles__is_set);
       __typeMapper.writeString(__out, State__typeInfo, State, State__is_set);
       __typeMapper.writeString(__out, Street__typeInfo, Street, Street__is_set);
       __typeMapper.writeString(__out, Title__typeInfo, Title, Title__is_set);
       __typeMapper.writeObject(__out, UpdatedDate__typeInfo, UpdatedDate, UpdatedDate__is_set);
       __typeMapper.writeString(__out, Zip__typeInfo, Zip, Zip__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        super.loadFields(__in, __typeMapper);
        __in.peekTag();
        if (__typeMapper.isElement(__in, City__typeInfo)) {
            setCity(__typeMapper.readString(__in, City__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CompanyId__typeInfo)) {
            setCompanyId(__typeMapper.readString(__in, CompanyId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CompanyName__typeInfo)) {
            setCompanyName(__typeMapper.readString(__in, CompanyName__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ContactId__typeInfo)) {
            setContactId(__typeMapper.readString(__in, ContactId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Country__typeInfo)) {
            setCountry(__typeMapper.readString(__in, Country__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Department__typeInfo)) {
            setDepartment(__typeMapper.readString(__in, Department__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Email__typeInfo)) {
            setEmail(__typeMapper.readString(__in, Email__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ExternalId__typeInfo)) {
            setExternalId(__typeMapper.readString(__in, ExternalId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, FirstName__typeInfo)) {
            setFirstName(__typeMapper.readString(__in, FirstName__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, IsInactive__typeInfo)) {
            setIsInactive((java.lang.Boolean)__typeMapper.readObject(__in, IsInactive__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, IsOwned__typeInfo)) {
            setIsOwned((java.lang.Boolean)__typeMapper.readObject(__in, IsOwned__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, LastName__typeInfo)) {
            setLastName(__typeMapper.readString(__in, LastName__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Level__typeInfo)) {
            setLevel(__typeMapper.readString(__in, Level__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Phone__typeInfo)) {
            setPhone(__typeMapper.readString(__in, Phone__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, SocialHandles__typeInfo)) {
            setSocialHandles((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, SocialHandles__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, State__typeInfo)) {
            setState(__typeMapper.readString(__in, State__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Street__typeInfo)) {
            setStreet(__typeMapper.readString(__in, Street__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Title__typeInfo)) {
            setTitle(__typeMapper.readString(__in, Title__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, UpdatedDate__typeInfo)) {
            setUpdatedDate((java.util.Calendar)__typeMapper.readObject(__in, UpdatedDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Zip__typeInfo)) {
            setZip(__typeMapper.readString(__in, Zip__typeInfo, java.lang.String.class));
        }
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[DatacloudContact ");
      sb.append(super.toString());sb.append(" City='").append(com.sforce.ws.util.Verbose.toString(City)).append("'\n");
      sb.append(" CompanyId='").append(com.sforce.ws.util.Verbose.toString(CompanyId)).append("'\n");
      sb.append(" CompanyName='").append(com.sforce.ws.util.Verbose.toString(CompanyName)).append("'\n");
      sb.append(" ContactId='").append(com.sforce.ws.util.Verbose.toString(ContactId)).append("'\n");
      sb.append(" Country='").append(com.sforce.ws.util.Verbose.toString(Country)).append("'\n");
      sb.append(" Department='").append(com.sforce.ws.util.Verbose.toString(Department)).append("'\n");
      sb.append(" Email='").append(com.sforce.ws.util.Verbose.toString(Email)).append("'\n");
      sb.append(" ExternalId='").append(com.sforce.ws.util.Verbose.toString(ExternalId)).append("'\n");
      sb.append(" FirstName='").append(com.sforce.ws.util.Verbose.toString(FirstName)).append("'\n");
      sb.append(" IsInactive='").append(com.sforce.ws.util.Verbose.toString(IsInactive)).append("'\n");
      sb.append(" IsOwned='").append(com.sforce.ws.util.Verbose.toString(IsOwned)).append("'\n");
      sb.append(" LastName='").append(com.sforce.ws.util.Verbose.toString(LastName)).append("'\n");
      sb.append(" Level='").append(com.sforce.ws.util.Verbose.toString(Level)).append("'\n");
      sb.append(" Phone='").append(com.sforce.ws.util.Verbose.toString(Phone)).append("'\n");
      sb.append(" SocialHandles='").append(com.sforce.ws.util.Verbose.toString(SocialHandles)).append("'\n");
      sb.append(" State='").append(com.sforce.ws.util.Verbose.toString(State)).append("'\n");
      sb.append(" Street='").append(com.sforce.ws.util.Verbose.toString(Street)).append("'\n");
      sb.append(" Title='").append(com.sforce.ws.util.Verbose.toString(Title)).append("'\n");
      sb.append(" UpdatedDate='").append(com.sforce.ws.util.Verbose.toString(UpdatedDate)).append("'\n");
      sb.append(" Zip='").append(com.sforce.ws.util.Verbose.toString(Zip)).append("'\n");
      sb.append("]\n");
      return sb.toString();
    }

}
