package com.sforce.soap.enterprise.sobject;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class DatacloudCompany extends com.sforce.soap.enterprise.sobject.SObject {

    /**
     * Constructor
     */
    public DatacloudCompany() {}

    /**
     * element : ActiveContacts of type {http://www.w3.org/2001/XMLSchema}int
     * java type: java.lang.Integer
     */
    private static final com.sforce.ws.bind.TypeInfo ActiveContacts__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ActiveContacts","http://www.w3.org/2001/XMLSchema","int",0,1,true);

    private boolean ActiveContacts__is_set = false;

    private java.lang.Integer ActiveContacts;

    public java.lang.Integer getActiveContacts() {
      return ActiveContacts;
    }

    public void setActiveContacts(java.lang.Integer ActiveContacts) {
      this.ActiveContacts = ActiveContacts;
      ActiveContacts__is_set = true;
    }

    /**
     * element : AnnualRevenue of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo AnnualRevenue__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","AnnualRevenue","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean AnnualRevenue__is_set = false;

    private java.lang.Double AnnualRevenue;

    public java.lang.Double getAnnualRevenue() {
      return AnnualRevenue;
    }

    public void setAnnualRevenue(java.lang.Double AnnualRevenue) {
      this.AnnualRevenue = AnnualRevenue;
      AnnualRevenue__is_set = true;
    }

    /**
     * element : City of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo City__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","City","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean City__is_set = false;

    private java.lang.String City;

    public java.lang.String getCity() {
      return City;
    }

    public void setCity(java.lang.String City) {
      this.City = City;
      City__is_set = true;
    }

    /**
     * element : CompanyId of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo CompanyId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CompanyId","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean CompanyId__is_set = false;

    private java.lang.String CompanyId;

    public java.lang.String getCompanyId() {
      return CompanyId;
    }

    public void setCompanyId(java.lang.String CompanyId) {
      this.CompanyId = CompanyId;
      CompanyId__is_set = true;
    }

    /**
     * element : Country of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Country__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Country","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Country__is_set = false;

    private java.lang.String Country;

    public java.lang.String getCountry() {
      return Country;
    }

    public void setCountry(java.lang.String Country) {
      this.Country = Country;
      Country__is_set = true;
    }

    /**
     * element : Description of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Description__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Description","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Description__is_set = false;

    private java.lang.String Description;

    public java.lang.String getDescription() {
      return Description;
    }

    public void setDescription(java.lang.String Description) {
      this.Description = Description;
      Description__is_set = true;
    }

    /**
     * element : DunsNumber of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo DunsNumber__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","DunsNumber","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean DunsNumber__is_set = false;

    private java.lang.String DunsNumber;

    public java.lang.String getDunsNumber() {
      return DunsNumber;
    }

    public void setDunsNumber(java.lang.String DunsNumber) {
      this.DunsNumber = DunsNumber;
      DunsNumber__is_set = true;
    }

    /**
     * element : ExternalId of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ExternalId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ExternalId","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean ExternalId__is_set = false;

    private java.lang.String ExternalId;

    public java.lang.String getExternalId() {
      return ExternalId;
    }

    public void setExternalId(java.lang.String ExternalId) {
      this.ExternalId = ExternalId;
      ExternalId__is_set = true;
    }

    /**
     * element : Fax of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Fax__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Fax","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Fax__is_set = false;

    private java.lang.String Fax;

    public java.lang.String getFax() {
      return Fax;
    }

    public void setFax(java.lang.String Fax) {
      this.Fax = Fax;
      Fax__is_set = true;
    }

    /**
     * element : Industry of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Industry__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Industry","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Industry__is_set = false;

    private java.lang.String Industry;

    public java.lang.String getIndustry() {
      return Industry;
    }

    public void setIndustry(java.lang.String Industry) {
      this.Industry = Industry;
      Industry__is_set = true;
    }

    /**
     * element : IsInactive of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo IsInactive__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","IsInactive","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean IsInactive__is_set = false;

    private java.lang.Boolean IsInactive;

    public java.lang.Boolean getIsInactive() {
      return IsInactive;
    }

    public void setIsInactive(java.lang.Boolean IsInactive) {
      this.IsInactive = IsInactive;
      IsInactive__is_set = true;
    }

    /**
     * element : IsOwned of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo IsOwned__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","IsOwned","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean IsOwned__is_set = false;

    private java.lang.Boolean IsOwned;

    public java.lang.Boolean getIsOwned() {
      return IsOwned;
    }

    public void setIsOwned(java.lang.Boolean IsOwned) {
      this.IsOwned = IsOwned;
      IsOwned__is_set = true;
    }

    /**
     * element : NaicsCode of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo NaicsCode__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","NaicsCode","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean NaicsCode__is_set = false;

    private java.lang.String NaicsCode;

    public java.lang.String getNaicsCode() {
      return NaicsCode;
    }

    public void setNaicsCode(java.lang.String NaicsCode) {
      this.NaicsCode = NaicsCode;
      NaicsCode__is_set = true;
    }

    /**
     * element : NaicsDesc of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo NaicsDesc__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","NaicsDesc","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean NaicsDesc__is_set = false;

    private java.lang.String NaicsDesc;

    public java.lang.String getNaicsDesc() {
      return NaicsDesc;
    }

    public void setNaicsDesc(java.lang.String NaicsDesc) {
      this.NaicsDesc = NaicsDesc;
      NaicsDesc__is_set = true;
    }

    /**
     * element : Name of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Name__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Name","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Name__is_set = false;

    private java.lang.String Name;

    public java.lang.String getName() {
      return Name;
    }

    public void setName(java.lang.String Name) {
      this.Name = Name;
      Name__is_set = true;
    }

    /**
     * element : NumberOfEmployees of type {http://www.w3.org/2001/XMLSchema}int
     * java type: java.lang.Integer
     */
    private static final com.sforce.ws.bind.TypeInfo NumberOfEmployees__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","NumberOfEmployees","http://www.w3.org/2001/XMLSchema","int",0,1,true);

    private boolean NumberOfEmployees__is_set = false;

    private java.lang.Integer NumberOfEmployees;

    public java.lang.Integer getNumberOfEmployees() {
      return NumberOfEmployees;
    }

    public void setNumberOfEmployees(java.lang.Integer NumberOfEmployees) {
      this.NumberOfEmployees = NumberOfEmployees;
      NumberOfEmployees__is_set = true;
    }

    /**
     * element : Ownership of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Ownership__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Ownership","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Ownership__is_set = false;

    private java.lang.String Ownership;

    public java.lang.String getOwnership() {
      return Ownership;
    }

    public void setOwnership(java.lang.String Ownership) {
      this.Ownership = Ownership;
      Ownership__is_set = true;
    }

    /**
     * element : Phone of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Phone__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Phone","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Phone__is_set = false;

    private java.lang.String Phone;

    public java.lang.String getPhone() {
      return Phone;
    }

    public void setPhone(java.lang.String Phone) {
      this.Phone = Phone;
      Phone__is_set = true;
    }

    /**
     * element : Sic of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Sic__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Sic","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Sic__is_set = false;

    private java.lang.String Sic;

    public java.lang.String getSic() {
      return Sic;
    }

    public void setSic(java.lang.String Sic) {
      this.Sic = Sic;
      Sic__is_set = true;
    }

    /**
     * element : SicDesc of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo SicDesc__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","SicDesc","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean SicDesc__is_set = false;

    private java.lang.String SicDesc;

    public java.lang.String getSicDesc() {
      return SicDesc;
    }

    public void setSicDesc(java.lang.String SicDesc) {
      this.SicDesc = SicDesc;
      SicDesc__is_set = true;
    }

    /**
     * element : Site of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Site__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Site","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Site__is_set = false;

    private java.lang.String Site;

    public java.lang.String getSite() {
      return Site;
    }

    public void setSite(java.lang.String Site) {
      this.Site = Site;
      Site__is_set = true;
    }

    /**
     * element : State of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo State__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","State","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean State__is_set = false;

    private java.lang.String State;

    public java.lang.String getState() {
      return State;
    }

    public void setState(java.lang.String State) {
      this.State = State;
      State__is_set = true;
    }

    /**
     * element : Street of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Street__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Street","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Street__is_set = false;

    private java.lang.String Street;

    public java.lang.String getStreet() {
      return Street;
    }

    public void setStreet(java.lang.String Street) {
      this.Street = Street;
      Street__is_set = true;
    }

    /**
     * element : TickerSymbol of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo TickerSymbol__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","TickerSymbol","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean TickerSymbol__is_set = false;

    private java.lang.String TickerSymbol;

    public java.lang.String getTickerSymbol() {
      return TickerSymbol;
    }

    public void setTickerSymbol(java.lang.String TickerSymbol) {
      this.TickerSymbol = TickerSymbol;
      TickerSymbol__is_set = true;
    }

    /**
     * element : TradeStyle of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo TradeStyle__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","TradeStyle","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean TradeStyle__is_set = false;

    private java.lang.String TradeStyle;

    public java.lang.String getTradeStyle() {
      return TradeStyle;
    }

    public void setTradeStyle(java.lang.String TradeStyle) {
      this.TradeStyle = TradeStyle;
      TradeStyle__is_set = true;
    }

    /**
     * element : UpdatedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo UpdatedDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","UpdatedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean UpdatedDate__is_set = false;

    private java.util.Calendar UpdatedDate;

    public java.util.Calendar getUpdatedDate() {
      return UpdatedDate;
    }

    public void setUpdatedDate(java.util.Calendar UpdatedDate) {
      this.UpdatedDate = UpdatedDate;
      UpdatedDate__is_set = true;
    }

    /**
     * element : Website of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Website__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Website","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Website__is_set = false;

    private java.lang.String Website;

    public java.lang.String getWebsite() {
      return Website;
    }

    public void setWebsite(java.lang.String Website) {
      this.Website = Website;
      Website__is_set = true;
    }

    /**
     * element : YearStarted of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo YearStarted__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","YearStarted","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean YearStarted__is_set = false;

    private java.lang.String YearStarted;

    public java.lang.String getYearStarted() {
      return YearStarted;
    }

    public void setYearStarted(java.lang.String YearStarted) {
      this.YearStarted = YearStarted;
      YearStarted__is_set = true;
    }

    /**
     * element : Zip of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Zip__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Zip","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Zip__is_set = false;

    private java.lang.String Zip;

    public java.lang.String getZip() {
      return Zip;
    }

    public void setZip(java.lang.String Zip) {
      this.Zip = Zip;
      Zip__is_set = true;
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      __typeMapper.writeXsiType(__out, "urn:sobject.enterprise.soap.sforce.com", "DatacloudCompany");
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       super.writeFields(__out, __typeMapper);
       __typeMapper.writeObject(__out, ActiveContacts__typeInfo, ActiveContacts, ActiveContacts__is_set);
       __typeMapper.writeObject(__out, AnnualRevenue__typeInfo, AnnualRevenue, AnnualRevenue__is_set);
       __typeMapper.writeString(__out, City__typeInfo, City, City__is_set);
       __typeMapper.writeString(__out, CompanyId__typeInfo, CompanyId, CompanyId__is_set);
       __typeMapper.writeString(__out, Country__typeInfo, Country, Country__is_set);
       __typeMapper.writeString(__out, Description__typeInfo, Description, Description__is_set);
       __typeMapper.writeString(__out, DunsNumber__typeInfo, DunsNumber, DunsNumber__is_set);
       __typeMapper.writeString(__out, ExternalId__typeInfo, ExternalId, ExternalId__is_set);
       __typeMapper.writeString(__out, Fax__typeInfo, Fax, Fax__is_set);
       __typeMapper.writeString(__out, Industry__typeInfo, Industry, Industry__is_set);
       __typeMapper.writeObject(__out, IsInactive__typeInfo, IsInactive, IsInactive__is_set);
       __typeMapper.writeObject(__out, IsOwned__typeInfo, IsOwned, IsOwned__is_set);
       __typeMapper.writeString(__out, NaicsCode__typeInfo, NaicsCode, NaicsCode__is_set);
       __typeMapper.writeString(__out, NaicsDesc__typeInfo, NaicsDesc, NaicsDesc__is_set);
       __typeMapper.writeString(__out, Name__typeInfo, Name, Name__is_set);
       __typeMapper.writeObject(__out, NumberOfEmployees__typeInfo, NumberOfEmployees, NumberOfEmployees__is_set);
       __typeMapper.writeString(__out, Ownership__typeInfo, Ownership, Ownership__is_set);
       __typeMapper.writeString(__out, Phone__typeInfo, Phone, Phone__is_set);
       __typeMapper.writeString(__out, Sic__typeInfo, Sic, Sic__is_set);
       __typeMapper.writeString(__out, SicDesc__typeInfo, SicDesc, SicDesc__is_set);
       __typeMapper.writeString(__out, Site__typeInfo, Site, Site__is_set);
       __typeMapper.writeString(__out, State__typeInfo, State, State__is_set);
       __typeMapper.writeString(__out, Street__typeInfo, Street, Street__is_set);
       __typeMapper.writeString(__out, TickerSymbol__typeInfo, TickerSymbol, TickerSymbol__is_set);
       __typeMapper.writeString(__out, TradeStyle__typeInfo, TradeStyle, TradeStyle__is_set);
       __typeMapper.writeObject(__out, UpdatedDate__typeInfo, UpdatedDate, UpdatedDate__is_set);
       __typeMapper.writeString(__out, Website__typeInfo, Website, Website__is_set);
       __typeMapper.writeString(__out, YearStarted__typeInfo, YearStarted, YearStarted__is_set);
       __typeMapper.writeString(__out, Zip__typeInfo, Zip, Zip__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        super.loadFields(__in, __typeMapper);
        __in.peekTag();
        if (__typeMapper.isElement(__in, ActiveContacts__typeInfo)) {
            setActiveContacts((java.lang.Integer)__typeMapper.readObject(__in, ActiveContacts__typeInfo, java.lang.Integer.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, AnnualRevenue__typeInfo)) {
            setAnnualRevenue((java.lang.Double)__typeMapper.readObject(__in, AnnualRevenue__typeInfo, java.lang.Double.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, City__typeInfo)) {
            setCity(__typeMapper.readString(__in, City__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CompanyId__typeInfo)) {
            setCompanyId(__typeMapper.readString(__in, CompanyId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Country__typeInfo)) {
            setCountry(__typeMapper.readString(__in, Country__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Description__typeInfo)) {
            setDescription(__typeMapper.readString(__in, Description__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, DunsNumber__typeInfo)) {
            setDunsNumber(__typeMapper.readString(__in, DunsNumber__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ExternalId__typeInfo)) {
            setExternalId(__typeMapper.readString(__in, ExternalId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Fax__typeInfo)) {
            setFax(__typeMapper.readString(__in, Fax__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Industry__typeInfo)) {
            setIndustry(__typeMapper.readString(__in, Industry__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, IsInactive__typeInfo)) {
            setIsInactive((java.lang.Boolean)__typeMapper.readObject(__in, IsInactive__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, IsOwned__typeInfo)) {
            setIsOwned((java.lang.Boolean)__typeMapper.readObject(__in, IsOwned__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, NaicsCode__typeInfo)) {
            setNaicsCode(__typeMapper.readString(__in, NaicsCode__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, NaicsDesc__typeInfo)) {
            setNaicsDesc(__typeMapper.readString(__in, NaicsDesc__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Name__typeInfo)) {
            setName(__typeMapper.readString(__in, Name__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, NumberOfEmployees__typeInfo)) {
            setNumberOfEmployees((java.lang.Integer)__typeMapper.readObject(__in, NumberOfEmployees__typeInfo, java.lang.Integer.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Ownership__typeInfo)) {
            setOwnership(__typeMapper.readString(__in, Ownership__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Phone__typeInfo)) {
            setPhone(__typeMapper.readString(__in, Phone__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Sic__typeInfo)) {
            setSic(__typeMapper.readString(__in, Sic__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, SicDesc__typeInfo)) {
            setSicDesc(__typeMapper.readString(__in, SicDesc__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Site__typeInfo)) {
            setSite(__typeMapper.readString(__in, Site__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, State__typeInfo)) {
            setState(__typeMapper.readString(__in, State__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Street__typeInfo)) {
            setStreet(__typeMapper.readString(__in, Street__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, TickerSymbol__typeInfo)) {
            setTickerSymbol(__typeMapper.readString(__in, TickerSymbol__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, TradeStyle__typeInfo)) {
            setTradeStyle(__typeMapper.readString(__in, TradeStyle__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, UpdatedDate__typeInfo)) {
            setUpdatedDate((java.util.Calendar)__typeMapper.readObject(__in, UpdatedDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Website__typeInfo)) {
            setWebsite(__typeMapper.readString(__in, Website__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, YearStarted__typeInfo)) {
            setYearStarted(__typeMapper.readString(__in, YearStarted__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Zip__typeInfo)) {
            setZip(__typeMapper.readString(__in, Zip__typeInfo, java.lang.String.class));
        }
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[DatacloudCompany ");
      sb.append(super.toString());sb.append(" ActiveContacts='").append(com.sforce.ws.util.Verbose.toString(ActiveContacts)).append("'\n");
      sb.append(" AnnualRevenue='").append(com.sforce.ws.util.Verbose.toString(AnnualRevenue)).append("'\n");
      sb.append(" City='").append(com.sforce.ws.util.Verbose.toString(City)).append("'\n");
      sb.append(" CompanyId='").append(com.sforce.ws.util.Verbose.toString(CompanyId)).append("'\n");
      sb.append(" Country='").append(com.sforce.ws.util.Verbose.toString(Country)).append("'\n");
      sb.append(" Description='").append(com.sforce.ws.util.Verbose.toString(Description)).append("'\n");
      sb.append(" DunsNumber='").append(com.sforce.ws.util.Verbose.toString(DunsNumber)).append("'\n");
      sb.append(" ExternalId='").append(com.sforce.ws.util.Verbose.toString(ExternalId)).append("'\n");
      sb.append(" Fax='").append(com.sforce.ws.util.Verbose.toString(Fax)).append("'\n");
      sb.append(" Industry='").append(com.sforce.ws.util.Verbose.toString(Industry)).append("'\n");
      sb.append(" IsInactive='").append(com.sforce.ws.util.Verbose.toString(IsInactive)).append("'\n");
      sb.append(" IsOwned='").append(com.sforce.ws.util.Verbose.toString(IsOwned)).append("'\n");
      sb.append(" NaicsCode='").append(com.sforce.ws.util.Verbose.toString(NaicsCode)).append("'\n");
      sb.append(" NaicsDesc='").append(com.sforce.ws.util.Verbose.toString(NaicsDesc)).append("'\n");
      sb.append(" Name='").append(com.sforce.ws.util.Verbose.toString(Name)).append("'\n");
      sb.append(" NumberOfEmployees='").append(com.sforce.ws.util.Verbose.toString(NumberOfEmployees)).append("'\n");
      sb.append(" Ownership='").append(com.sforce.ws.util.Verbose.toString(Ownership)).append("'\n");
      sb.append(" Phone='").append(com.sforce.ws.util.Verbose.toString(Phone)).append("'\n");
      sb.append(" Sic='").append(com.sforce.ws.util.Verbose.toString(Sic)).append("'\n");
      sb.append(" SicDesc='").append(com.sforce.ws.util.Verbose.toString(SicDesc)).append("'\n");
      sb.append(" Site='").append(com.sforce.ws.util.Verbose.toString(Site)).append("'\n");
      sb.append(" State='").append(com.sforce.ws.util.Verbose.toString(State)).append("'\n");
      sb.append(" Street='").append(com.sforce.ws.util.Verbose.toString(Street)).append("'\n");
      sb.append(" TickerSymbol='").append(com.sforce.ws.util.Verbose.toString(TickerSymbol)).append("'\n");
      sb.append(" TradeStyle='").append(com.sforce.ws.util.Verbose.toString(TradeStyle)).append("'\n");
      sb.append(" UpdatedDate='").append(com.sforce.ws.util.Verbose.toString(UpdatedDate)).append("'\n");
      sb.append(" Website='").append(com.sforce.ws.util.Verbose.toString(Website)).append("'\n");
      sb.append(" YearStarted='").append(com.sforce.ws.util.Verbose.toString(YearStarted)).append("'\n");
      sb.append(" Zip='").append(com.sforce.ws.util.Verbose.toString(Zip)).append("'\n");
      sb.append("]\n");
      return sb.toString();
    }

}
