package com.sforce.soap.enterprise.sobject;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class Order extends com.sforce.soap.enterprise.sobject.SObject {

    /**
     * Constructor
     */
    public Order() {}

    /**
     * element : Account of type {urn:sobject.enterprise.soap.sforce.com}Account
     * java type: com.sforce.soap.enterprise.sobject.Account
     */
    private static final com.sforce.ws.bind.TypeInfo Account__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Account","urn:sobject.enterprise.soap.sforce.com","Account",0,1,true);

    private boolean Account__is_set = false;

    private com.sforce.soap.enterprise.sobject.Account Account;

    public com.sforce.soap.enterprise.sobject.Account getAccount() {
      return Account;
    }

    public void setAccount(com.sforce.soap.enterprise.sobject.Account Account) {
      this.Account = Account;
      Account__is_set = true;
    }

    /**
     * element : AccountId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo AccountId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","AccountId","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean AccountId__is_set = false;

    private java.lang.String AccountId;

    public java.lang.String getAccountId() {
      return AccountId;
    }

    public void setAccountId(java.lang.String AccountId) {
      this.AccountId = AccountId;
      AccountId__is_set = true;
    }

    /**
     * element : ActivatedBy of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private static final com.sforce.ws.bind.TypeInfo ActivatedBy__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ActivatedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true);

    private boolean ActivatedBy__is_set = false;

    private com.sforce.soap.enterprise.sobject.User ActivatedBy;

    public com.sforce.soap.enterprise.sobject.User getActivatedBy() {
      return ActivatedBy;
    }

    public void setActivatedBy(com.sforce.soap.enterprise.sobject.User ActivatedBy) {
      this.ActivatedBy = ActivatedBy;
      ActivatedBy__is_set = true;
    }

    /**
     * element : ActivatedById of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ActivatedById__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ActivatedById","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean ActivatedById__is_set = false;

    private java.lang.String ActivatedById;

    public java.lang.String getActivatedById() {
      return ActivatedById;
    }

    public void setActivatedById(java.lang.String ActivatedById) {
      this.ActivatedById = ActivatedById;
      ActivatedById__is_set = true;
    }

    /**
     * element : ActivatedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo ActivatedDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ActivatedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean ActivatedDate__is_set = false;

    private java.util.Calendar ActivatedDate;

    public java.util.Calendar getActivatedDate() {
      return ActivatedDate;
    }

    public void setActivatedDate(java.util.Calendar ActivatedDate) {
      this.ActivatedDate = ActivatedDate;
      ActivatedDate__is_set = true;
    }

    /**
     * element : ActivityHistories of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo ActivityHistories__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ActivityHistories","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean ActivityHistories__is_set = false;

    private com.sforce.soap.enterprise.QueryResult ActivityHistories;

    public com.sforce.soap.enterprise.QueryResult getActivityHistories() {
      return ActivityHistories;
    }

    public void setActivityHistories(com.sforce.soap.enterprise.QueryResult ActivityHistories) {
      this.ActivityHistories = ActivityHistories;
      ActivityHistories__is_set = true;
    }

    /**
     * element : AttachedContentDocuments of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo AttachedContentDocuments__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","AttachedContentDocuments","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean AttachedContentDocuments__is_set = false;

    private com.sforce.soap.enterprise.QueryResult AttachedContentDocuments;

    public com.sforce.soap.enterprise.QueryResult getAttachedContentDocuments() {
      return AttachedContentDocuments;
    }

    public void setAttachedContentDocuments(com.sforce.soap.enterprise.QueryResult AttachedContentDocuments) {
      this.AttachedContentDocuments = AttachedContentDocuments;
      AttachedContentDocuments__is_set = true;
    }

    /**
     * element : Attachments of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo Attachments__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Attachments","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean Attachments__is_set = false;

    private com.sforce.soap.enterprise.QueryResult Attachments;

    public com.sforce.soap.enterprise.QueryResult getAttachments() {
      return Attachments;
    }

    public void setAttachments(com.sforce.soap.enterprise.QueryResult Attachments) {
      this.Attachments = Attachments;
      Attachments__is_set = true;
    }

    /**
     * element : BillToContact of type {urn:sobject.enterprise.soap.sforce.com}Contact
     * java type: com.sforce.soap.enterprise.sobject.Contact
     */
    private static final com.sforce.ws.bind.TypeInfo BillToContact__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","BillToContact","urn:sobject.enterprise.soap.sforce.com","Contact",0,1,true);

    private boolean BillToContact__is_set = false;

    private com.sforce.soap.enterprise.sobject.Contact BillToContact;

    public com.sforce.soap.enterprise.sobject.Contact getBillToContact() {
      return BillToContact;
    }

    public void setBillToContact(com.sforce.soap.enterprise.sobject.Contact BillToContact) {
      this.BillToContact = BillToContact;
      BillToContact__is_set = true;
    }

    /**
     * element : BillToContactId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo BillToContactId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","BillToContactId","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean BillToContactId__is_set = false;

    private java.lang.String BillToContactId;

    public java.lang.String getBillToContactId() {
      return BillToContactId;
    }

    public void setBillToContactId(java.lang.String BillToContactId) {
      this.BillToContactId = BillToContactId;
      BillToContactId__is_set = true;
    }

    /**
     * element : BillingAddress of type {urn:enterprise.soap.sforce.com}address
     * java type: com.sforce.soap.enterprise.Address
     */
    private static final com.sforce.ws.bind.TypeInfo BillingAddress__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","BillingAddress","urn:enterprise.soap.sforce.com","address",0,1,true);

    private boolean BillingAddress__is_set = false;

    private com.sforce.soap.enterprise.Address BillingAddress;

    public com.sforce.soap.enterprise.Address getBillingAddress() {
      return BillingAddress;
    }

    public void setBillingAddress(com.sforce.soap.enterprise.Address BillingAddress) {
      this.BillingAddress = BillingAddress;
      BillingAddress__is_set = true;
    }

    /**
     * element : BillingCity of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo BillingCity__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","BillingCity","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean BillingCity__is_set = false;

    private java.lang.String BillingCity;

    public java.lang.String getBillingCity() {
      return BillingCity;
    }

    public void setBillingCity(java.lang.String BillingCity) {
      this.BillingCity = BillingCity;
      BillingCity__is_set = true;
    }

    /**
     * element : BillingCountry of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo BillingCountry__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","BillingCountry","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean BillingCountry__is_set = false;

    private java.lang.String BillingCountry;

    public java.lang.String getBillingCountry() {
      return BillingCountry;
    }

    public void setBillingCountry(java.lang.String BillingCountry) {
      this.BillingCountry = BillingCountry;
      BillingCountry__is_set = true;
    }

    /**
     * element : BillingLatitude of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo BillingLatitude__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","BillingLatitude","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean BillingLatitude__is_set = false;

    private java.lang.Double BillingLatitude;

    public java.lang.Double getBillingLatitude() {
      return BillingLatitude;
    }

    public void setBillingLatitude(java.lang.Double BillingLatitude) {
      this.BillingLatitude = BillingLatitude;
      BillingLatitude__is_set = true;
    }

    /**
     * element : BillingLongitude of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo BillingLongitude__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","BillingLongitude","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean BillingLongitude__is_set = false;

    private java.lang.Double BillingLongitude;

    public java.lang.Double getBillingLongitude() {
      return BillingLongitude;
    }

    public void setBillingLongitude(java.lang.Double BillingLongitude) {
      this.BillingLongitude = BillingLongitude;
      BillingLongitude__is_set = true;
    }

    /**
     * element : BillingPostalCode of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo BillingPostalCode__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","BillingPostalCode","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean BillingPostalCode__is_set = false;

    private java.lang.String BillingPostalCode;

    public java.lang.String getBillingPostalCode() {
      return BillingPostalCode;
    }

    public void setBillingPostalCode(java.lang.String BillingPostalCode) {
      this.BillingPostalCode = BillingPostalCode;
      BillingPostalCode__is_set = true;
    }

    /**
     * element : BillingState of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo BillingState__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","BillingState","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean BillingState__is_set = false;

    private java.lang.String BillingState;

    public java.lang.String getBillingState() {
      return BillingState;
    }

    public void setBillingState(java.lang.String BillingState) {
      this.BillingState = BillingState;
      BillingState__is_set = true;
    }

    /**
     * element : BillingStreet of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo BillingStreet__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","BillingStreet","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean BillingStreet__is_set = false;

    private java.lang.String BillingStreet;

    public java.lang.String getBillingStreet() {
      return BillingStreet;
    }

    public void setBillingStreet(java.lang.String BillingStreet) {
      this.BillingStreet = BillingStreet;
      BillingStreet__is_set = true;
    }

    /**
     * element : CombinedAttachments of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo CombinedAttachments__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CombinedAttachments","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean CombinedAttachments__is_set = false;

    private com.sforce.soap.enterprise.QueryResult CombinedAttachments;

    public com.sforce.soap.enterprise.QueryResult getCombinedAttachments() {
      return CombinedAttachments;
    }

    public void setCombinedAttachments(com.sforce.soap.enterprise.QueryResult CombinedAttachments) {
      this.CombinedAttachments = CombinedAttachments;
      CombinedAttachments__is_set = true;
    }

    /**
     * element : CompanyAuthorizedBy of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private static final com.sforce.ws.bind.TypeInfo CompanyAuthorizedBy__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CompanyAuthorizedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true);

    private boolean CompanyAuthorizedBy__is_set = false;

    private com.sforce.soap.enterprise.sobject.User CompanyAuthorizedBy;

    public com.sforce.soap.enterprise.sobject.User getCompanyAuthorizedBy() {
      return CompanyAuthorizedBy;
    }

    public void setCompanyAuthorizedBy(com.sforce.soap.enterprise.sobject.User CompanyAuthorizedBy) {
      this.CompanyAuthorizedBy = CompanyAuthorizedBy;
      CompanyAuthorizedBy__is_set = true;
    }

    /**
     * element : CompanyAuthorizedById of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo CompanyAuthorizedById__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CompanyAuthorizedById","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean CompanyAuthorizedById__is_set = false;

    private java.lang.String CompanyAuthorizedById;

    public java.lang.String getCompanyAuthorizedById() {
      return CompanyAuthorizedById;
    }

    public void setCompanyAuthorizedById(java.lang.String CompanyAuthorizedById) {
      this.CompanyAuthorizedById = CompanyAuthorizedById;
      CompanyAuthorizedById__is_set = true;
    }

    /**
     * element : CompanyAuthorizedDate of type {http://www.w3.org/2001/XMLSchema}date
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo CompanyAuthorizedDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CompanyAuthorizedDate","http://www.w3.org/2001/XMLSchema","date",0,1,true);

    private boolean CompanyAuthorizedDate__is_set = false;

    private java.util.Calendar CompanyAuthorizedDate;

    public java.util.Calendar getCompanyAuthorizedDate() {
      return CompanyAuthorizedDate;
    }

    public void setCompanyAuthorizedDate(java.util.Calendar CompanyAuthorizedDate) {
      this.CompanyAuthorizedDate = CompanyAuthorizedDate;
      CompanyAuthorizedDate__is_set = true;
    }

    /**
     * element : Contract of type {urn:sobject.enterprise.soap.sforce.com}Contract
     * java type: com.sforce.soap.enterprise.sobject.Contract
     */
    private static final com.sforce.ws.bind.TypeInfo Contract__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Contract","urn:sobject.enterprise.soap.sforce.com","Contract",0,1,true);

    private boolean Contract__is_set = false;

    private com.sforce.soap.enterprise.sobject.Contract Contract;

    public com.sforce.soap.enterprise.sobject.Contract getContract() {
      return Contract;
    }

    public void setContract(com.sforce.soap.enterprise.sobject.Contract Contract) {
      this.Contract = Contract;
      Contract__is_set = true;
    }

    /**
     * element : ContractId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ContractId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ContractId","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean ContractId__is_set = false;

    private java.lang.String ContractId;

    public java.lang.String getContractId() {
      return ContractId;
    }

    public void setContractId(java.lang.String ContractId) {
      this.ContractId = ContractId;
      ContractId__is_set = true;
    }

    /**
     * element : CreatedBy of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private static final com.sforce.ws.bind.TypeInfo CreatedBy__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CreatedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true);

    private boolean CreatedBy__is_set = false;

    private com.sforce.soap.enterprise.sobject.User CreatedBy;

    public com.sforce.soap.enterprise.sobject.User getCreatedBy() {
      return CreatedBy;
    }

    public void setCreatedBy(com.sforce.soap.enterprise.sobject.User CreatedBy) {
      this.CreatedBy = CreatedBy;
      CreatedBy__is_set = true;
    }

    /**
     * element : CreatedById of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo CreatedById__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CreatedById","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean CreatedById__is_set = false;

    private java.lang.String CreatedById;

    public java.lang.String getCreatedById() {
      return CreatedById;
    }

    public void setCreatedById(java.lang.String CreatedById) {
      this.CreatedById = CreatedById;
      CreatedById__is_set = true;
    }

    /**
     * element : CreatedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo CreatedDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CreatedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean CreatedDate__is_set = false;

    private java.util.Calendar CreatedDate;

    public java.util.Calendar getCreatedDate() {
      return CreatedDate;
    }

    public void setCreatedDate(java.util.Calendar CreatedDate) {
      this.CreatedDate = CreatedDate;
      CreatedDate__is_set = true;
    }

    /**
     * element : CustomerAuthorizedBy of type {urn:sobject.enterprise.soap.sforce.com}Contact
     * java type: com.sforce.soap.enterprise.sobject.Contact
     */
    private static final com.sforce.ws.bind.TypeInfo CustomerAuthorizedBy__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CustomerAuthorizedBy","urn:sobject.enterprise.soap.sforce.com","Contact",0,1,true);

    private boolean CustomerAuthorizedBy__is_set = false;

    private com.sforce.soap.enterprise.sobject.Contact CustomerAuthorizedBy;

    public com.sforce.soap.enterprise.sobject.Contact getCustomerAuthorizedBy() {
      return CustomerAuthorizedBy;
    }

    public void setCustomerAuthorizedBy(com.sforce.soap.enterprise.sobject.Contact CustomerAuthorizedBy) {
      this.CustomerAuthorizedBy = CustomerAuthorizedBy;
      CustomerAuthorizedBy__is_set = true;
    }

    /**
     * element : CustomerAuthorizedById of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo CustomerAuthorizedById__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CustomerAuthorizedById","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean CustomerAuthorizedById__is_set = false;

    private java.lang.String CustomerAuthorizedById;

    public java.lang.String getCustomerAuthorizedById() {
      return CustomerAuthorizedById;
    }

    public void setCustomerAuthorizedById(java.lang.String CustomerAuthorizedById) {
      this.CustomerAuthorizedById = CustomerAuthorizedById;
      CustomerAuthorizedById__is_set = true;
    }

    /**
     * element : CustomerAuthorizedDate of type {http://www.w3.org/2001/XMLSchema}date
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo CustomerAuthorizedDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CustomerAuthorizedDate","http://www.w3.org/2001/XMLSchema","date",0,1,true);

    private boolean CustomerAuthorizedDate__is_set = false;

    private java.util.Calendar CustomerAuthorizedDate;

    public java.util.Calendar getCustomerAuthorizedDate() {
      return CustomerAuthorizedDate;
    }

    public void setCustomerAuthorizedDate(java.util.Calendar CustomerAuthorizedDate) {
      this.CustomerAuthorizedDate = CustomerAuthorizedDate;
      CustomerAuthorizedDate__is_set = true;
    }

    /**
     * element : Description of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Description__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Description","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Description__is_set = false;

    private java.lang.String Description;

    public java.lang.String getDescription() {
      return Description;
    }

    public void setDescription(java.lang.String Description) {
      this.Description = Description;
      Description__is_set = true;
    }

    /**
     * element : EffectiveDate of type {http://www.w3.org/2001/XMLSchema}date
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo EffectiveDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","EffectiveDate","http://www.w3.org/2001/XMLSchema","date",0,1,true);

    private boolean EffectiveDate__is_set = false;

    private java.util.Calendar EffectiveDate;

    public java.util.Calendar getEffectiveDate() {
      return EffectiveDate;
    }

    public void setEffectiveDate(java.util.Calendar EffectiveDate) {
      this.EffectiveDate = EffectiveDate;
      EffectiveDate__is_set = true;
    }

    /**
     * element : EndDate of type {http://www.w3.org/2001/XMLSchema}date
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo EndDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","EndDate","http://www.w3.org/2001/XMLSchema","date",0,1,true);

    private boolean EndDate__is_set = false;

    private java.util.Calendar EndDate;

    public java.util.Calendar getEndDate() {
      return EndDate;
    }

    public void setEndDate(java.util.Calendar EndDate) {
      this.EndDate = EndDate;
      EndDate__is_set = true;
    }

    /**
     * element : Events of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo Events__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Events","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean Events__is_set = false;

    private com.sforce.soap.enterprise.QueryResult Events;

    public com.sforce.soap.enterprise.QueryResult getEvents() {
      return Events;
    }

    public void setEvents(com.sforce.soap.enterprise.QueryResult Events) {
      this.Events = Events;
      Events__is_set = true;
    }

    /**
     * element : FeedSubscriptionsForEntity of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo FeedSubscriptionsForEntity__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","FeedSubscriptionsForEntity","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean FeedSubscriptionsForEntity__is_set = false;

    private com.sforce.soap.enterprise.QueryResult FeedSubscriptionsForEntity;

    public com.sforce.soap.enterprise.QueryResult getFeedSubscriptionsForEntity() {
      return FeedSubscriptionsForEntity;
    }

    public void setFeedSubscriptionsForEntity(com.sforce.soap.enterprise.QueryResult FeedSubscriptionsForEntity) {
      this.FeedSubscriptionsForEntity = FeedSubscriptionsForEntity;
      FeedSubscriptionsForEntity__is_set = true;
    }

    /**
     * element : Feeds of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo Feeds__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Feeds","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean Feeds__is_set = false;

    private com.sforce.soap.enterprise.QueryResult Feeds;

    public com.sforce.soap.enterprise.QueryResult getFeeds() {
      return Feeds;
    }

    public void setFeeds(com.sforce.soap.enterprise.QueryResult Feeds) {
      this.Feeds = Feeds;
      Feeds__is_set = true;
    }

    /**
     * element : Histories of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo Histories__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Histories","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean Histories__is_set = false;

    private com.sforce.soap.enterprise.QueryResult Histories;

    public com.sforce.soap.enterprise.QueryResult getHistories() {
      return Histories;
    }

    public void setHistories(com.sforce.soap.enterprise.QueryResult Histories) {
      this.Histories = Histories;
      Histories__is_set = true;
    }

    /**
     * element : IsDeleted of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo IsDeleted__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","IsDeleted","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean IsDeleted__is_set = false;

    private java.lang.Boolean IsDeleted;

    public java.lang.Boolean getIsDeleted() {
      return IsDeleted;
    }

    public void setIsDeleted(java.lang.Boolean IsDeleted) {
      this.IsDeleted = IsDeleted;
      IsDeleted__is_set = true;
    }

    /**
     * element : IsReductionOrder of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo IsReductionOrder__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","IsReductionOrder","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean IsReductionOrder__is_set = false;

    private java.lang.Boolean IsReductionOrder;

    public java.lang.Boolean getIsReductionOrder() {
      return IsReductionOrder;
    }

    public void setIsReductionOrder(java.lang.Boolean IsReductionOrder) {
      this.IsReductionOrder = IsReductionOrder;
      IsReductionOrder__is_set = true;
    }

    /**
     * element : LastModifiedBy of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private static final com.sforce.ws.bind.TypeInfo LastModifiedBy__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","LastModifiedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true);

    private boolean LastModifiedBy__is_set = false;

    private com.sforce.soap.enterprise.sobject.User LastModifiedBy;

    public com.sforce.soap.enterprise.sobject.User getLastModifiedBy() {
      return LastModifiedBy;
    }

    public void setLastModifiedBy(com.sforce.soap.enterprise.sobject.User LastModifiedBy) {
      this.LastModifiedBy = LastModifiedBy;
      LastModifiedBy__is_set = true;
    }

    /**
     * element : LastModifiedById of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo LastModifiedById__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","LastModifiedById","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean LastModifiedById__is_set = false;

    private java.lang.String LastModifiedById;

    public java.lang.String getLastModifiedById() {
      return LastModifiedById;
    }

    public void setLastModifiedById(java.lang.String LastModifiedById) {
      this.LastModifiedById = LastModifiedById;
      LastModifiedById__is_set = true;
    }

    /**
     * element : LastModifiedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo LastModifiedDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","LastModifiedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean LastModifiedDate__is_set = false;

    private java.util.Calendar LastModifiedDate;

    public java.util.Calendar getLastModifiedDate() {
      return LastModifiedDate;
    }

    public void setLastModifiedDate(java.util.Calendar LastModifiedDate) {
      this.LastModifiedDate = LastModifiedDate;
      LastModifiedDate__is_set = true;
    }

    /**
     * element : LastReferencedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo LastReferencedDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","LastReferencedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean LastReferencedDate__is_set = false;

    private java.util.Calendar LastReferencedDate;

    public java.util.Calendar getLastReferencedDate() {
      return LastReferencedDate;
    }

    public void setLastReferencedDate(java.util.Calendar LastReferencedDate) {
      this.LastReferencedDate = LastReferencedDate;
      LastReferencedDate__is_set = true;
    }

    /**
     * element : LastViewedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo LastViewedDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","LastViewedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean LastViewedDate__is_set = false;

    private java.util.Calendar LastViewedDate;

    public java.util.Calendar getLastViewedDate() {
      return LastViewedDate;
    }

    public void setLastViewedDate(java.util.Calendar LastViewedDate) {
      this.LastViewedDate = LastViewedDate;
      LastViewedDate__is_set = true;
    }

    /**
     * element : LookedUpFromActivities of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo LookedUpFromActivities__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","LookedUpFromActivities","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean LookedUpFromActivities__is_set = false;

    private com.sforce.soap.enterprise.QueryResult LookedUpFromActivities;

    public com.sforce.soap.enterprise.QueryResult getLookedUpFromActivities() {
      return LookedUpFromActivities;
    }

    public void setLookedUpFromActivities(com.sforce.soap.enterprise.QueryResult LookedUpFromActivities) {
      this.LookedUpFromActivities = LookedUpFromActivities;
      LookedUpFromActivities__is_set = true;
    }

    /**
     * element : Name of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Name__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Name","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Name__is_set = false;

    private java.lang.String Name;

    public java.lang.String getName() {
      return Name;
    }

    public void setName(java.lang.String Name) {
      this.Name = Name;
      Name__is_set = true;
    }

    /**
     * element : Notes of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo Notes__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Notes","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean Notes__is_set = false;

    private com.sforce.soap.enterprise.QueryResult Notes;

    public com.sforce.soap.enterprise.QueryResult getNotes() {
      return Notes;
    }

    public void setNotes(com.sforce.soap.enterprise.QueryResult Notes) {
      this.Notes = Notes;
      Notes__is_set = true;
    }

    /**
     * element : NotesAndAttachments of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo NotesAndAttachments__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","NotesAndAttachments","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean NotesAndAttachments__is_set = false;

    private com.sforce.soap.enterprise.QueryResult NotesAndAttachments;

    public com.sforce.soap.enterprise.QueryResult getNotesAndAttachments() {
      return NotesAndAttachments;
    }

    public void setNotesAndAttachments(com.sforce.soap.enterprise.QueryResult NotesAndAttachments) {
      this.NotesAndAttachments = NotesAndAttachments;
      NotesAndAttachments__is_set = true;
    }

    /**
     * element : OpenActivities of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo OpenActivities__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","OpenActivities","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean OpenActivities__is_set = false;

    private com.sforce.soap.enterprise.QueryResult OpenActivities;

    public com.sforce.soap.enterprise.QueryResult getOpenActivities() {
      return OpenActivities;
    }

    public void setOpenActivities(com.sforce.soap.enterprise.QueryResult OpenActivities) {
      this.OpenActivities = OpenActivities;
      OpenActivities__is_set = true;
    }

    /**
     * element : OrderItems of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo OrderItems__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","OrderItems","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean OrderItems__is_set = false;

    private com.sforce.soap.enterprise.QueryResult OrderItems;

    public com.sforce.soap.enterprise.QueryResult getOrderItems() {
      return OrderItems;
    }

    public void setOrderItems(com.sforce.soap.enterprise.QueryResult OrderItems) {
      this.OrderItems = OrderItems;
      OrderItems__is_set = true;
    }

    /**
     * element : OrderNumber of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo OrderNumber__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","OrderNumber","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean OrderNumber__is_set = false;

    private java.lang.String OrderNumber;

    public java.lang.String getOrderNumber() {
      return OrderNumber;
    }

    public void setOrderNumber(java.lang.String OrderNumber) {
      this.OrderNumber = OrderNumber;
      OrderNumber__is_set = true;
    }

    /**
     * element : OrderReferenceNumber of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo OrderReferenceNumber__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","OrderReferenceNumber","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean OrderReferenceNumber__is_set = false;

    private java.lang.String OrderReferenceNumber;

    public java.lang.String getOrderReferenceNumber() {
      return OrderReferenceNumber;
    }

    public void setOrderReferenceNumber(java.lang.String OrderReferenceNumber) {
      this.OrderReferenceNumber = OrderReferenceNumber;
      OrderReferenceNumber__is_set = true;
    }

    /**
     * element : Orders of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo Orders__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Orders","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean Orders__is_set = false;

    private com.sforce.soap.enterprise.QueryResult Orders;

    public com.sforce.soap.enterprise.QueryResult getOrders() {
      return Orders;
    }

    public void setOrders(com.sforce.soap.enterprise.QueryResult Orders) {
      this.Orders = Orders;
      Orders__is_set = true;
    }

    /**
     * element : OriginalOrder of type {urn:sobject.enterprise.soap.sforce.com}Order
     * java type: com.sforce.soap.enterprise.sobject.Order
     */
    private static final com.sforce.ws.bind.TypeInfo OriginalOrder__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","OriginalOrder","urn:sobject.enterprise.soap.sforce.com","Order",0,1,true);

    private boolean OriginalOrder__is_set = false;

    private com.sforce.soap.enterprise.sobject.Order OriginalOrder;

    public com.sforce.soap.enterprise.sobject.Order getOriginalOrder() {
      return OriginalOrder;
    }

    public void setOriginalOrder(com.sforce.soap.enterprise.sobject.Order OriginalOrder) {
      this.OriginalOrder = OriginalOrder;
      OriginalOrder__is_set = true;
    }

    /**
     * element : OriginalOrderId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo OriginalOrderId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","OriginalOrderId","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean OriginalOrderId__is_set = false;

    private java.lang.String OriginalOrderId;

    public java.lang.String getOriginalOrderId() {
      return OriginalOrderId;
    }

    public void setOriginalOrderId(java.lang.String OriginalOrderId) {
      this.OriginalOrderId = OriginalOrderId;
      OriginalOrderId__is_set = true;
    }

    /**
     * element : Owner of type {urn:sobject.enterprise.soap.sforce.com}sObject
     * java type: com.sforce.soap.enterprise.sobject.SObject
     */
    private static final com.sforce.ws.bind.TypeInfo Owner__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Owner","urn:sobject.enterprise.soap.sforce.com","sObject",0,1,true);

    private boolean Owner__is_set = false;

    private com.sforce.soap.enterprise.sobject.SObject Owner;

    public com.sforce.soap.enterprise.sobject.SObject getOwner() {
      return Owner;
    }

    public void setOwner(com.sforce.soap.enterprise.sobject.SObject Owner) {
      this.Owner = Owner;
      Owner__is_set = true;
    }

    /**
     * element : OwnerId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo OwnerId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","OwnerId","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean OwnerId__is_set = false;

    private java.lang.String OwnerId;

    public java.lang.String getOwnerId() {
      return OwnerId;
    }

    public void setOwnerId(java.lang.String OwnerId) {
      this.OwnerId = OwnerId;
      OwnerId__is_set = true;
    }

    /**
     * element : PoDate of type {http://www.w3.org/2001/XMLSchema}date
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo PoDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","PoDate","http://www.w3.org/2001/XMLSchema","date",0,1,true);

    private boolean PoDate__is_set = false;

    private java.util.Calendar PoDate;

    public java.util.Calendar getPoDate() {
      return PoDate;
    }

    public void setPoDate(java.util.Calendar PoDate) {
      this.PoDate = PoDate;
      PoDate__is_set = true;
    }

    /**
     * element : PoNumber of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo PoNumber__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","PoNumber","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean PoNumber__is_set = false;

    private java.lang.String PoNumber;

    public java.lang.String getPoNumber() {
      return PoNumber;
    }

    public void setPoNumber(java.lang.String PoNumber) {
      this.PoNumber = PoNumber;
      PoNumber__is_set = true;
    }

    /**
     * element : Pricebook2 of type {urn:sobject.enterprise.soap.sforce.com}Pricebook2
     * java type: com.sforce.soap.enterprise.sobject.Pricebook2
     */
    private static final com.sforce.ws.bind.TypeInfo Pricebook2__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Pricebook2","urn:sobject.enterprise.soap.sforce.com","Pricebook2",0,1,true);

    private boolean Pricebook2__is_set = false;

    private com.sforce.soap.enterprise.sobject.Pricebook2 Pricebook2;

    public com.sforce.soap.enterprise.sobject.Pricebook2 getPricebook2() {
      return Pricebook2;
    }

    public void setPricebook2(com.sforce.soap.enterprise.sobject.Pricebook2 Pricebook2) {
      this.Pricebook2 = Pricebook2;
      Pricebook2__is_set = true;
    }

    /**
     * element : Pricebook2Id of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Pricebook2Id__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Pricebook2Id","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean Pricebook2Id__is_set = false;

    private java.lang.String Pricebook2Id;

    public java.lang.String getPricebook2Id() {
      return Pricebook2Id;
    }

    public void setPricebook2Id(java.lang.String Pricebook2Id) {
      this.Pricebook2Id = Pricebook2Id;
      Pricebook2Id__is_set = true;
    }

    /**
     * element : ProcessInstances of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo ProcessInstances__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ProcessInstances","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean ProcessInstances__is_set = false;

    private com.sforce.soap.enterprise.QueryResult ProcessInstances;

    public com.sforce.soap.enterprise.QueryResult getProcessInstances() {
      return ProcessInstances;
    }

    public void setProcessInstances(com.sforce.soap.enterprise.QueryResult ProcessInstances) {
      this.ProcessInstances = ProcessInstances;
      ProcessInstances__is_set = true;
    }

    /**
     * element : ProcessSteps of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo ProcessSteps__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ProcessSteps","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean ProcessSteps__is_set = false;

    private com.sforce.soap.enterprise.QueryResult ProcessSteps;

    public com.sforce.soap.enterprise.QueryResult getProcessSteps() {
      return ProcessSteps;
    }

    public void setProcessSteps(com.sforce.soap.enterprise.QueryResult ProcessSteps) {
      this.ProcessSteps = ProcessSteps;
      ProcessSteps__is_set = true;
    }

    /**
     * element : ShipToContact of type {urn:sobject.enterprise.soap.sforce.com}Contact
     * java type: com.sforce.soap.enterprise.sobject.Contact
     */
    private static final com.sforce.ws.bind.TypeInfo ShipToContact__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ShipToContact","urn:sobject.enterprise.soap.sforce.com","Contact",0,1,true);

    private boolean ShipToContact__is_set = false;

    private com.sforce.soap.enterprise.sobject.Contact ShipToContact;

    public com.sforce.soap.enterprise.sobject.Contact getShipToContact() {
      return ShipToContact;
    }

    public void setShipToContact(com.sforce.soap.enterprise.sobject.Contact ShipToContact) {
      this.ShipToContact = ShipToContact;
      ShipToContact__is_set = true;
    }

    /**
     * element : ShipToContactId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ShipToContactId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ShipToContactId","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean ShipToContactId__is_set = false;

    private java.lang.String ShipToContactId;

    public java.lang.String getShipToContactId() {
      return ShipToContactId;
    }

    public void setShipToContactId(java.lang.String ShipToContactId) {
      this.ShipToContactId = ShipToContactId;
      ShipToContactId__is_set = true;
    }

    /**
     * element : ShippingAddress of type {urn:enterprise.soap.sforce.com}address
     * java type: com.sforce.soap.enterprise.Address
     */
    private static final com.sforce.ws.bind.TypeInfo ShippingAddress__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ShippingAddress","urn:enterprise.soap.sforce.com","address",0,1,true);

    private boolean ShippingAddress__is_set = false;

    private com.sforce.soap.enterprise.Address ShippingAddress;

    public com.sforce.soap.enterprise.Address getShippingAddress() {
      return ShippingAddress;
    }

    public void setShippingAddress(com.sforce.soap.enterprise.Address ShippingAddress) {
      this.ShippingAddress = ShippingAddress;
      ShippingAddress__is_set = true;
    }

    /**
     * element : ShippingCity of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ShippingCity__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ShippingCity","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean ShippingCity__is_set = false;

    private java.lang.String ShippingCity;

    public java.lang.String getShippingCity() {
      return ShippingCity;
    }

    public void setShippingCity(java.lang.String ShippingCity) {
      this.ShippingCity = ShippingCity;
      ShippingCity__is_set = true;
    }

    /**
     * element : ShippingCountry of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ShippingCountry__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ShippingCountry","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean ShippingCountry__is_set = false;

    private java.lang.String ShippingCountry;

    public java.lang.String getShippingCountry() {
      return ShippingCountry;
    }

    public void setShippingCountry(java.lang.String ShippingCountry) {
      this.ShippingCountry = ShippingCountry;
      ShippingCountry__is_set = true;
    }

    /**
     * element : ShippingLatitude of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo ShippingLatitude__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ShippingLatitude","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean ShippingLatitude__is_set = false;

    private java.lang.Double ShippingLatitude;

    public java.lang.Double getShippingLatitude() {
      return ShippingLatitude;
    }

    public void setShippingLatitude(java.lang.Double ShippingLatitude) {
      this.ShippingLatitude = ShippingLatitude;
      ShippingLatitude__is_set = true;
    }

    /**
     * element : ShippingLongitude of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo ShippingLongitude__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ShippingLongitude","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean ShippingLongitude__is_set = false;

    private java.lang.Double ShippingLongitude;

    public java.lang.Double getShippingLongitude() {
      return ShippingLongitude;
    }

    public void setShippingLongitude(java.lang.Double ShippingLongitude) {
      this.ShippingLongitude = ShippingLongitude;
      ShippingLongitude__is_set = true;
    }

    /**
     * element : ShippingPostalCode of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ShippingPostalCode__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ShippingPostalCode","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean ShippingPostalCode__is_set = false;

    private java.lang.String ShippingPostalCode;

    public java.lang.String getShippingPostalCode() {
      return ShippingPostalCode;
    }

    public void setShippingPostalCode(java.lang.String ShippingPostalCode) {
      this.ShippingPostalCode = ShippingPostalCode;
      ShippingPostalCode__is_set = true;
    }

    /**
     * element : ShippingState of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ShippingState__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ShippingState","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean ShippingState__is_set = false;

    private java.lang.String ShippingState;

    public java.lang.String getShippingState() {
      return ShippingState;
    }

    public void setShippingState(java.lang.String ShippingState) {
      this.ShippingState = ShippingState;
      ShippingState__is_set = true;
    }

    /**
     * element : ShippingStreet of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ShippingStreet__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ShippingStreet","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean ShippingStreet__is_set = false;

    private java.lang.String ShippingStreet;

    public java.lang.String getShippingStreet() {
      return ShippingStreet;
    }

    public void setShippingStreet(java.lang.String ShippingStreet) {
      this.ShippingStreet = ShippingStreet;
      ShippingStreet__is_set = true;
    }

    /**
     * element : Status of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Status__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Status","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Status__is_set = false;

    private java.lang.String Status;

    public java.lang.String getStatus() {
      return Status;
    }

    public void setStatus(java.lang.String Status) {
      this.Status = Status;
      Status__is_set = true;
    }

    /**
     * element : StatusCode of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo StatusCode__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","StatusCode","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean StatusCode__is_set = false;

    private java.lang.String StatusCode;

    public java.lang.String getStatusCode() {
      return StatusCode;
    }

    public void setStatusCode(java.lang.String StatusCode) {
      this.StatusCode = StatusCode;
      StatusCode__is_set = true;
    }

    /**
     * element : SystemModstamp of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo SystemModstamp__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","SystemModstamp","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean SystemModstamp__is_set = false;

    private java.util.Calendar SystemModstamp;

    public java.util.Calendar getSystemModstamp() {
      return SystemModstamp;
    }

    public void setSystemModstamp(java.util.Calendar SystemModstamp) {
      this.SystemModstamp = SystemModstamp;
      SystemModstamp__is_set = true;
    }

    /**
     * element : Tasks of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo Tasks__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Tasks","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean Tasks__is_set = false;

    private com.sforce.soap.enterprise.QueryResult Tasks;

    public com.sforce.soap.enterprise.QueryResult getTasks() {
      return Tasks;
    }

    public void setTasks(com.sforce.soap.enterprise.QueryResult Tasks) {
      this.Tasks = Tasks;
      Tasks__is_set = true;
    }

    /**
     * element : TopicAssignments of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo TopicAssignments__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","TopicAssignments","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean TopicAssignments__is_set = false;

    private com.sforce.soap.enterprise.QueryResult TopicAssignments;

    public com.sforce.soap.enterprise.QueryResult getTopicAssignments() {
      return TopicAssignments;
    }

    public void setTopicAssignments(com.sforce.soap.enterprise.QueryResult TopicAssignments) {
      this.TopicAssignments = TopicAssignments;
      TopicAssignments__is_set = true;
    }

    /**
     * element : TotalAmount of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo TotalAmount__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","TotalAmount","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean TotalAmount__is_set = false;

    private java.lang.Double TotalAmount;

    public java.lang.Double getTotalAmount() {
      return TotalAmount;
    }

    public void setTotalAmount(java.lang.Double TotalAmount) {
      this.TotalAmount = TotalAmount;
      TotalAmount__is_set = true;
    }

    /**
     * element : Type of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Type__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Type","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Type__is_set = false;

    private java.lang.String Type;

    public java.lang.String getType() {
      return Type;
    }

    public void setType(java.lang.String Type) {
      this.Type = Type;
      Type__is_set = true;
    }

    /**
     * element : UserRecordAccess of type {urn:sobject.enterprise.soap.sforce.com}UserRecordAccess
     * java type: com.sforce.soap.enterprise.sobject.UserRecordAccess
     */
    private static final com.sforce.ws.bind.TypeInfo UserRecordAccess__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","UserRecordAccess","urn:sobject.enterprise.soap.sforce.com","UserRecordAccess",0,1,true);

    private boolean UserRecordAccess__is_set = false;

    private com.sforce.soap.enterprise.sobject.UserRecordAccess UserRecordAccess;

    public com.sforce.soap.enterprise.sobject.UserRecordAccess getUserRecordAccess() {
      return UserRecordAccess;
    }

    public void setUserRecordAccess(com.sforce.soap.enterprise.sobject.UserRecordAccess UserRecordAccess) {
      this.UserRecordAccess = UserRecordAccess;
      UserRecordAccess__is_set = true;
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      __typeMapper.writeXsiType(__out, "urn:sobject.enterprise.soap.sforce.com", "Order");
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       super.writeFields(__out, __typeMapper);
       __typeMapper.writeObject(__out, Account__typeInfo, Account, Account__is_set);
       __typeMapper.writeString(__out, AccountId__typeInfo, AccountId, AccountId__is_set);
       __typeMapper.writeObject(__out, ActivatedBy__typeInfo, ActivatedBy, ActivatedBy__is_set);
       __typeMapper.writeString(__out, ActivatedById__typeInfo, ActivatedById, ActivatedById__is_set);
       __typeMapper.writeObject(__out, ActivatedDate__typeInfo, ActivatedDate, ActivatedDate__is_set);
       __typeMapper.writeObject(__out, ActivityHistories__typeInfo, ActivityHistories, ActivityHistories__is_set);
       __typeMapper.writeObject(__out, AttachedContentDocuments__typeInfo, AttachedContentDocuments, AttachedContentDocuments__is_set);
       __typeMapper.writeObject(__out, Attachments__typeInfo, Attachments, Attachments__is_set);
       __typeMapper.writeObject(__out, BillToContact__typeInfo, BillToContact, BillToContact__is_set);
       __typeMapper.writeString(__out, BillToContactId__typeInfo, BillToContactId, BillToContactId__is_set);
       __typeMapper.writeObject(__out, BillingAddress__typeInfo, BillingAddress, BillingAddress__is_set);
       __typeMapper.writeString(__out, BillingCity__typeInfo, BillingCity, BillingCity__is_set);
       __typeMapper.writeString(__out, BillingCountry__typeInfo, BillingCountry, BillingCountry__is_set);
       __typeMapper.writeObject(__out, BillingLatitude__typeInfo, BillingLatitude, BillingLatitude__is_set);
       __typeMapper.writeObject(__out, BillingLongitude__typeInfo, BillingLongitude, BillingLongitude__is_set);
       __typeMapper.writeString(__out, BillingPostalCode__typeInfo, BillingPostalCode, BillingPostalCode__is_set);
       __typeMapper.writeString(__out, BillingState__typeInfo, BillingState, BillingState__is_set);
       __typeMapper.writeString(__out, BillingStreet__typeInfo, BillingStreet, BillingStreet__is_set);
       __typeMapper.writeObject(__out, CombinedAttachments__typeInfo, CombinedAttachments, CombinedAttachments__is_set);
       __typeMapper.writeObject(__out, CompanyAuthorizedBy__typeInfo, CompanyAuthorizedBy, CompanyAuthorizedBy__is_set);
       __typeMapper.writeString(__out, CompanyAuthorizedById__typeInfo, CompanyAuthorizedById, CompanyAuthorizedById__is_set);
       __typeMapper.writeObject(__out, CompanyAuthorizedDate__typeInfo, CompanyAuthorizedDate, CompanyAuthorizedDate__is_set);
       __typeMapper.writeObject(__out, Contract__typeInfo, Contract, Contract__is_set);
       __typeMapper.writeString(__out, ContractId__typeInfo, ContractId, ContractId__is_set);
       __typeMapper.writeObject(__out, CreatedBy__typeInfo, CreatedBy, CreatedBy__is_set);
       __typeMapper.writeString(__out, CreatedById__typeInfo, CreatedById, CreatedById__is_set);
       __typeMapper.writeObject(__out, CreatedDate__typeInfo, CreatedDate, CreatedDate__is_set);
       __typeMapper.writeObject(__out, CustomerAuthorizedBy__typeInfo, CustomerAuthorizedBy, CustomerAuthorizedBy__is_set);
       __typeMapper.writeString(__out, CustomerAuthorizedById__typeInfo, CustomerAuthorizedById, CustomerAuthorizedById__is_set);
       __typeMapper.writeObject(__out, CustomerAuthorizedDate__typeInfo, CustomerAuthorizedDate, CustomerAuthorizedDate__is_set);
       __typeMapper.writeString(__out, Description__typeInfo, Description, Description__is_set);
       __typeMapper.writeObject(__out, EffectiveDate__typeInfo, EffectiveDate, EffectiveDate__is_set);
       __typeMapper.writeObject(__out, EndDate__typeInfo, EndDate, EndDate__is_set);
       __typeMapper.writeObject(__out, Events__typeInfo, Events, Events__is_set);
       __typeMapper.writeObject(__out, FeedSubscriptionsForEntity__typeInfo, FeedSubscriptionsForEntity, FeedSubscriptionsForEntity__is_set);
       __typeMapper.writeObject(__out, Feeds__typeInfo, Feeds, Feeds__is_set);
       __typeMapper.writeObject(__out, Histories__typeInfo, Histories, Histories__is_set);
       __typeMapper.writeObject(__out, IsDeleted__typeInfo, IsDeleted, IsDeleted__is_set);
       __typeMapper.writeObject(__out, IsReductionOrder__typeInfo, IsReductionOrder, IsReductionOrder__is_set);
       __typeMapper.writeObject(__out, LastModifiedBy__typeInfo, LastModifiedBy, LastModifiedBy__is_set);
       __typeMapper.writeString(__out, LastModifiedById__typeInfo, LastModifiedById, LastModifiedById__is_set);
       __typeMapper.writeObject(__out, LastModifiedDate__typeInfo, LastModifiedDate, LastModifiedDate__is_set);
       __typeMapper.writeObject(__out, LastReferencedDate__typeInfo, LastReferencedDate, LastReferencedDate__is_set);
       __typeMapper.writeObject(__out, LastViewedDate__typeInfo, LastViewedDate, LastViewedDate__is_set);
       __typeMapper.writeObject(__out, LookedUpFromActivities__typeInfo, LookedUpFromActivities, LookedUpFromActivities__is_set);
       __typeMapper.writeString(__out, Name__typeInfo, Name, Name__is_set);
       __typeMapper.writeObject(__out, Notes__typeInfo, Notes, Notes__is_set);
       __typeMapper.writeObject(__out, NotesAndAttachments__typeInfo, NotesAndAttachments, NotesAndAttachments__is_set);
       __typeMapper.writeObject(__out, OpenActivities__typeInfo, OpenActivities, OpenActivities__is_set);
       __typeMapper.writeObject(__out, OrderItems__typeInfo, OrderItems, OrderItems__is_set);
       __typeMapper.writeString(__out, OrderNumber__typeInfo, OrderNumber, OrderNumber__is_set);
       __typeMapper.writeString(__out, OrderReferenceNumber__typeInfo, OrderReferenceNumber, OrderReferenceNumber__is_set);
       __typeMapper.writeObject(__out, Orders__typeInfo, Orders, Orders__is_set);
       __typeMapper.writeObject(__out, OriginalOrder__typeInfo, OriginalOrder, OriginalOrder__is_set);
       __typeMapper.writeString(__out, OriginalOrderId__typeInfo, OriginalOrderId, OriginalOrderId__is_set);
       __typeMapper.writeObject(__out, Owner__typeInfo, Owner, Owner__is_set);
       __typeMapper.writeString(__out, OwnerId__typeInfo, OwnerId, OwnerId__is_set);
       __typeMapper.writeObject(__out, PoDate__typeInfo, PoDate, PoDate__is_set);
       __typeMapper.writeString(__out, PoNumber__typeInfo, PoNumber, PoNumber__is_set);
       __typeMapper.writeObject(__out, Pricebook2__typeInfo, Pricebook2, Pricebook2__is_set);
       __typeMapper.writeString(__out, Pricebook2Id__typeInfo, Pricebook2Id, Pricebook2Id__is_set);
       __typeMapper.writeObject(__out, ProcessInstances__typeInfo, ProcessInstances, ProcessInstances__is_set);
       __typeMapper.writeObject(__out, ProcessSteps__typeInfo, ProcessSteps, ProcessSteps__is_set);
       __typeMapper.writeObject(__out, ShipToContact__typeInfo, ShipToContact, ShipToContact__is_set);
       __typeMapper.writeString(__out, ShipToContactId__typeInfo, ShipToContactId, ShipToContactId__is_set);
       __typeMapper.writeObject(__out, ShippingAddress__typeInfo, ShippingAddress, ShippingAddress__is_set);
       __typeMapper.writeString(__out, ShippingCity__typeInfo, ShippingCity, ShippingCity__is_set);
       __typeMapper.writeString(__out, ShippingCountry__typeInfo, ShippingCountry, ShippingCountry__is_set);
       __typeMapper.writeObject(__out, ShippingLatitude__typeInfo, ShippingLatitude, ShippingLatitude__is_set);
       __typeMapper.writeObject(__out, ShippingLongitude__typeInfo, ShippingLongitude, ShippingLongitude__is_set);
       __typeMapper.writeString(__out, ShippingPostalCode__typeInfo, ShippingPostalCode, ShippingPostalCode__is_set);
       __typeMapper.writeString(__out, ShippingState__typeInfo, ShippingState, ShippingState__is_set);
       __typeMapper.writeString(__out, ShippingStreet__typeInfo, ShippingStreet, ShippingStreet__is_set);
       __typeMapper.writeString(__out, Status__typeInfo, Status, Status__is_set);
       __typeMapper.writeString(__out, StatusCode__typeInfo, StatusCode, StatusCode__is_set);
       __typeMapper.writeObject(__out, SystemModstamp__typeInfo, SystemModstamp, SystemModstamp__is_set);
       __typeMapper.writeObject(__out, Tasks__typeInfo, Tasks, Tasks__is_set);
       __typeMapper.writeObject(__out, TopicAssignments__typeInfo, TopicAssignments, TopicAssignments__is_set);
       __typeMapper.writeObject(__out, TotalAmount__typeInfo, TotalAmount, TotalAmount__is_set);
       __typeMapper.writeString(__out, Type__typeInfo, Type, Type__is_set);
       __typeMapper.writeObject(__out, UserRecordAccess__typeInfo, UserRecordAccess, UserRecordAccess__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        super.loadFields(__in, __typeMapper);
        __in.peekTag();
        if (__typeMapper.isElement(__in, Account__typeInfo)) {
            setAccount((com.sforce.soap.enterprise.sobject.Account)__typeMapper.readObject(__in, Account__typeInfo, com.sforce.soap.enterprise.sobject.Account.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, AccountId__typeInfo)) {
            setAccountId(__typeMapper.readString(__in, AccountId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ActivatedBy__typeInfo)) {
            setActivatedBy((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, ActivatedBy__typeInfo, com.sforce.soap.enterprise.sobject.User.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ActivatedById__typeInfo)) {
            setActivatedById(__typeMapper.readString(__in, ActivatedById__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ActivatedDate__typeInfo)) {
            setActivatedDate((java.util.Calendar)__typeMapper.readObject(__in, ActivatedDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ActivityHistories__typeInfo)) {
            setActivityHistories((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, ActivityHistories__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, AttachedContentDocuments__typeInfo)) {
            setAttachedContentDocuments((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, AttachedContentDocuments__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Attachments__typeInfo)) {
            setAttachments((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, Attachments__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, BillToContact__typeInfo)) {
            setBillToContact((com.sforce.soap.enterprise.sobject.Contact)__typeMapper.readObject(__in, BillToContact__typeInfo, com.sforce.soap.enterprise.sobject.Contact.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, BillToContactId__typeInfo)) {
            setBillToContactId(__typeMapper.readString(__in, BillToContactId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, BillingAddress__typeInfo)) {
            setBillingAddress((com.sforce.soap.enterprise.Address)__typeMapper.readObject(__in, BillingAddress__typeInfo, com.sforce.soap.enterprise.Address.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, BillingCity__typeInfo)) {
            setBillingCity(__typeMapper.readString(__in, BillingCity__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, BillingCountry__typeInfo)) {
            setBillingCountry(__typeMapper.readString(__in, BillingCountry__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, BillingLatitude__typeInfo)) {
            setBillingLatitude((java.lang.Double)__typeMapper.readObject(__in, BillingLatitude__typeInfo, java.lang.Double.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, BillingLongitude__typeInfo)) {
            setBillingLongitude((java.lang.Double)__typeMapper.readObject(__in, BillingLongitude__typeInfo, java.lang.Double.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, BillingPostalCode__typeInfo)) {
            setBillingPostalCode(__typeMapper.readString(__in, BillingPostalCode__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, BillingState__typeInfo)) {
            setBillingState(__typeMapper.readString(__in, BillingState__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, BillingStreet__typeInfo)) {
            setBillingStreet(__typeMapper.readString(__in, BillingStreet__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CombinedAttachments__typeInfo)) {
            setCombinedAttachments((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, CombinedAttachments__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CompanyAuthorizedBy__typeInfo)) {
            setCompanyAuthorizedBy((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, CompanyAuthorizedBy__typeInfo, com.sforce.soap.enterprise.sobject.User.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CompanyAuthorizedById__typeInfo)) {
            setCompanyAuthorizedById(__typeMapper.readString(__in, CompanyAuthorizedById__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CompanyAuthorizedDate__typeInfo)) {
            setCompanyAuthorizedDate((java.util.Calendar)__typeMapper.readObject(__in, CompanyAuthorizedDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Contract__typeInfo)) {
            setContract((com.sforce.soap.enterprise.sobject.Contract)__typeMapper.readObject(__in, Contract__typeInfo, com.sforce.soap.enterprise.sobject.Contract.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ContractId__typeInfo)) {
            setContractId(__typeMapper.readString(__in, ContractId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CreatedBy__typeInfo)) {
            setCreatedBy((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, CreatedBy__typeInfo, com.sforce.soap.enterprise.sobject.User.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CreatedById__typeInfo)) {
            setCreatedById(__typeMapper.readString(__in, CreatedById__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CreatedDate__typeInfo)) {
            setCreatedDate((java.util.Calendar)__typeMapper.readObject(__in, CreatedDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CustomerAuthorizedBy__typeInfo)) {
            setCustomerAuthorizedBy((com.sforce.soap.enterprise.sobject.Contact)__typeMapper.readObject(__in, CustomerAuthorizedBy__typeInfo, com.sforce.soap.enterprise.sobject.Contact.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CustomerAuthorizedById__typeInfo)) {
            setCustomerAuthorizedById(__typeMapper.readString(__in, CustomerAuthorizedById__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CustomerAuthorizedDate__typeInfo)) {
            setCustomerAuthorizedDate((java.util.Calendar)__typeMapper.readObject(__in, CustomerAuthorizedDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Description__typeInfo)) {
            setDescription(__typeMapper.readString(__in, Description__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, EffectiveDate__typeInfo)) {
            setEffectiveDate((java.util.Calendar)__typeMapper.readObject(__in, EffectiveDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, EndDate__typeInfo)) {
            setEndDate((java.util.Calendar)__typeMapper.readObject(__in, EndDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Events__typeInfo)) {
            setEvents((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, Events__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, FeedSubscriptionsForEntity__typeInfo)) {
            setFeedSubscriptionsForEntity((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, FeedSubscriptionsForEntity__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Feeds__typeInfo)) {
            setFeeds((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, Feeds__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Histories__typeInfo)) {
            setHistories((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, Histories__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, IsDeleted__typeInfo)) {
            setIsDeleted((java.lang.Boolean)__typeMapper.readObject(__in, IsDeleted__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, IsReductionOrder__typeInfo)) {
            setIsReductionOrder((java.lang.Boolean)__typeMapper.readObject(__in, IsReductionOrder__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, LastModifiedBy__typeInfo)) {
            setLastModifiedBy((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, LastModifiedBy__typeInfo, com.sforce.soap.enterprise.sobject.User.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, LastModifiedById__typeInfo)) {
            setLastModifiedById(__typeMapper.readString(__in, LastModifiedById__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, LastModifiedDate__typeInfo)) {
            setLastModifiedDate((java.util.Calendar)__typeMapper.readObject(__in, LastModifiedDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, LastReferencedDate__typeInfo)) {
            setLastReferencedDate((java.util.Calendar)__typeMapper.readObject(__in, LastReferencedDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, LastViewedDate__typeInfo)) {
            setLastViewedDate((java.util.Calendar)__typeMapper.readObject(__in, LastViewedDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, LookedUpFromActivities__typeInfo)) {
            setLookedUpFromActivities((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, LookedUpFromActivities__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Name__typeInfo)) {
            setName(__typeMapper.readString(__in, Name__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Notes__typeInfo)) {
            setNotes((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, Notes__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, NotesAndAttachments__typeInfo)) {
            setNotesAndAttachments((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, NotesAndAttachments__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, OpenActivities__typeInfo)) {
            setOpenActivities((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, OpenActivities__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, OrderItems__typeInfo)) {
            setOrderItems((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, OrderItems__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, OrderNumber__typeInfo)) {
            setOrderNumber(__typeMapper.readString(__in, OrderNumber__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, OrderReferenceNumber__typeInfo)) {
            setOrderReferenceNumber(__typeMapper.readString(__in, OrderReferenceNumber__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Orders__typeInfo)) {
            setOrders((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, Orders__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, OriginalOrder__typeInfo)) {
            setOriginalOrder((com.sforce.soap.enterprise.sobject.Order)__typeMapper.readObject(__in, OriginalOrder__typeInfo, com.sforce.soap.enterprise.sobject.Order.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, OriginalOrderId__typeInfo)) {
            setOriginalOrderId(__typeMapper.readString(__in, OriginalOrderId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Owner__typeInfo)) {
            setOwner((com.sforce.soap.enterprise.sobject.SObject)__typeMapper.readObject(__in, Owner__typeInfo, com.sforce.soap.enterprise.sobject.SObject.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, OwnerId__typeInfo)) {
            setOwnerId(__typeMapper.readString(__in, OwnerId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, PoDate__typeInfo)) {
            setPoDate((java.util.Calendar)__typeMapper.readObject(__in, PoDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, PoNumber__typeInfo)) {
            setPoNumber(__typeMapper.readString(__in, PoNumber__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Pricebook2__typeInfo)) {
            setPricebook2((com.sforce.soap.enterprise.sobject.Pricebook2)__typeMapper.readObject(__in, Pricebook2__typeInfo, com.sforce.soap.enterprise.sobject.Pricebook2.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Pricebook2Id__typeInfo)) {
            setPricebook2Id(__typeMapper.readString(__in, Pricebook2Id__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ProcessInstances__typeInfo)) {
            setProcessInstances((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, ProcessInstances__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ProcessSteps__typeInfo)) {
            setProcessSteps((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, ProcessSteps__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ShipToContact__typeInfo)) {
            setShipToContact((com.sforce.soap.enterprise.sobject.Contact)__typeMapper.readObject(__in, ShipToContact__typeInfo, com.sforce.soap.enterprise.sobject.Contact.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ShipToContactId__typeInfo)) {
            setShipToContactId(__typeMapper.readString(__in, ShipToContactId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ShippingAddress__typeInfo)) {
            setShippingAddress((com.sforce.soap.enterprise.Address)__typeMapper.readObject(__in, ShippingAddress__typeInfo, com.sforce.soap.enterprise.Address.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ShippingCity__typeInfo)) {
            setShippingCity(__typeMapper.readString(__in, ShippingCity__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ShippingCountry__typeInfo)) {
            setShippingCountry(__typeMapper.readString(__in, ShippingCountry__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ShippingLatitude__typeInfo)) {
            setShippingLatitude((java.lang.Double)__typeMapper.readObject(__in, ShippingLatitude__typeInfo, java.lang.Double.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ShippingLongitude__typeInfo)) {
            setShippingLongitude((java.lang.Double)__typeMapper.readObject(__in, ShippingLongitude__typeInfo, java.lang.Double.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ShippingPostalCode__typeInfo)) {
            setShippingPostalCode(__typeMapper.readString(__in, ShippingPostalCode__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ShippingState__typeInfo)) {
            setShippingState(__typeMapper.readString(__in, ShippingState__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ShippingStreet__typeInfo)) {
            setShippingStreet(__typeMapper.readString(__in, ShippingStreet__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Status__typeInfo)) {
            setStatus(__typeMapper.readString(__in, Status__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, StatusCode__typeInfo)) {
            setStatusCode(__typeMapper.readString(__in, StatusCode__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, SystemModstamp__typeInfo)) {
            setSystemModstamp((java.util.Calendar)__typeMapper.readObject(__in, SystemModstamp__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Tasks__typeInfo)) {
            setTasks((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, Tasks__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, TopicAssignments__typeInfo)) {
            setTopicAssignments((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, TopicAssignments__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, TotalAmount__typeInfo)) {
            setTotalAmount((java.lang.Double)__typeMapper.readObject(__in, TotalAmount__typeInfo, java.lang.Double.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Type__typeInfo)) {
            setType(__typeMapper.readString(__in, Type__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, UserRecordAccess__typeInfo)) {
            setUserRecordAccess((com.sforce.soap.enterprise.sobject.UserRecordAccess)__typeMapper.readObject(__in, UserRecordAccess__typeInfo, com.sforce.soap.enterprise.sobject.UserRecordAccess.class));
        }
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[Order ");
      sb.append(super.toString());sb.append(" Account='").append(com.sforce.ws.util.Verbose.toString(Account)).append("'\n");
      sb.append(" AccountId='").append(com.sforce.ws.util.Verbose.toString(AccountId)).append("'\n");
      sb.append(" ActivatedBy='").append(com.sforce.ws.util.Verbose.toString(ActivatedBy)).append("'\n");
      sb.append(" ActivatedById='").append(com.sforce.ws.util.Verbose.toString(ActivatedById)).append("'\n");
      sb.append(" ActivatedDate='").append(com.sforce.ws.util.Verbose.toString(ActivatedDate)).append("'\n");
      sb.append(" ActivityHistories='").append(com.sforce.ws.util.Verbose.toString(ActivityHistories)).append("'\n");
      sb.append(" AttachedContentDocuments='").append(com.sforce.ws.util.Verbose.toString(AttachedContentDocuments)).append("'\n");
      sb.append(" Attachments='").append(com.sforce.ws.util.Verbose.toString(Attachments)).append("'\n");
      sb.append(" BillToContact='").append(com.sforce.ws.util.Verbose.toString(BillToContact)).append("'\n");
      sb.append(" BillToContactId='").append(com.sforce.ws.util.Verbose.toString(BillToContactId)).append("'\n");
      sb.append(" BillingAddress='").append(com.sforce.ws.util.Verbose.toString(BillingAddress)).append("'\n");
      sb.append(" BillingCity='").append(com.sforce.ws.util.Verbose.toString(BillingCity)).append("'\n");
      sb.append(" BillingCountry='").append(com.sforce.ws.util.Verbose.toString(BillingCountry)).append("'\n");
      sb.append(" BillingLatitude='").append(com.sforce.ws.util.Verbose.toString(BillingLatitude)).append("'\n");
      sb.append(" BillingLongitude='").append(com.sforce.ws.util.Verbose.toString(BillingLongitude)).append("'\n");
      sb.append(" BillingPostalCode='").append(com.sforce.ws.util.Verbose.toString(BillingPostalCode)).append("'\n");
      sb.append(" BillingState='").append(com.sforce.ws.util.Verbose.toString(BillingState)).append("'\n");
      sb.append(" BillingStreet='").append(com.sforce.ws.util.Verbose.toString(BillingStreet)).append("'\n");
      sb.append(" CombinedAttachments='").append(com.sforce.ws.util.Verbose.toString(CombinedAttachments)).append("'\n");
      sb.append(" CompanyAuthorizedBy='").append(com.sforce.ws.util.Verbose.toString(CompanyAuthorizedBy)).append("'\n");
      sb.append(" CompanyAuthorizedById='").append(com.sforce.ws.util.Verbose.toString(CompanyAuthorizedById)).append("'\n");
      sb.append(" CompanyAuthorizedDate='").append(com.sforce.ws.util.Verbose.toString(CompanyAuthorizedDate)).append("'\n");
      sb.append(" Contract='").append(com.sforce.ws.util.Verbose.toString(Contract)).append("'\n");
      sb.append(" ContractId='").append(com.sforce.ws.util.Verbose.toString(ContractId)).append("'\n");
      sb.append(" CreatedBy='").append(com.sforce.ws.util.Verbose.toString(CreatedBy)).append("'\n");
      sb.append(" CreatedById='").append(com.sforce.ws.util.Verbose.toString(CreatedById)).append("'\n");
      sb.append(" CreatedDate='").append(com.sforce.ws.util.Verbose.toString(CreatedDate)).append("'\n");
      sb.append(" CustomerAuthorizedBy='").append(com.sforce.ws.util.Verbose.toString(CustomerAuthorizedBy)).append("'\n");
      sb.append(" CustomerAuthorizedById='").append(com.sforce.ws.util.Verbose.toString(CustomerAuthorizedById)).append("'\n");
      sb.append(" CustomerAuthorizedDate='").append(com.sforce.ws.util.Verbose.toString(CustomerAuthorizedDate)).append("'\n");
      sb.append(" Description='").append(com.sforce.ws.util.Verbose.toString(Description)).append("'\n");
      sb.append(" EffectiveDate='").append(com.sforce.ws.util.Verbose.toString(EffectiveDate)).append("'\n");
      sb.append(" EndDate='").append(com.sforce.ws.util.Verbose.toString(EndDate)).append("'\n");
      sb.append(" Events='").append(com.sforce.ws.util.Verbose.toString(Events)).append("'\n");
      sb.append(" FeedSubscriptionsForEntity='").append(com.sforce.ws.util.Verbose.toString(FeedSubscriptionsForEntity)).append("'\n");
      sb.append(" Feeds='").append(com.sforce.ws.util.Verbose.toString(Feeds)).append("'\n");
      sb.append(" Histories='").append(com.sforce.ws.util.Verbose.toString(Histories)).append("'\n");
      sb.append(" IsDeleted='").append(com.sforce.ws.util.Verbose.toString(IsDeleted)).append("'\n");
      sb.append(" IsReductionOrder='").append(com.sforce.ws.util.Verbose.toString(IsReductionOrder)).append("'\n");
      sb.append(" LastModifiedBy='").append(com.sforce.ws.util.Verbose.toString(LastModifiedBy)).append("'\n");
      sb.append(" LastModifiedById='").append(com.sforce.ws.util.Verbose.toString(LastModifiedById)).append("'\n");
      sb.append(" LastModifiedDate='").append(com.sforce.ws.util.Verbose.toString(LastModifiedDate)).append("'\n");
      sb.append(" LastReferencedDate='").append(com.sforce.ws.util.Verbose.toString(LastReferencedDate)).append("'\n");
      sb.append(" LastViewedDate='").append(com.sforce.ws.util.Verbose.toString(LastViewedDate)).append("'\n");
      sb.append(" LookedUpFromActivities='").append(com.sforce.ws.util.Verbose.toString(LookedUpFromActivities)).append("'\n");
      sb.append(" Name='").append(com.sforce.ws.util.Verbose.toString(Name)).append("'\n");
      sb.append(" Notes='").append(com.sforce.ws.util.Verbose.toString(Notes)).append("'\n");
      sb.append(" NotesAndAttachments='").append(com.sforce.ws.util.Verbose.toString(NotesAndAttachments)).append("'\n");
      sb.append(" OpenActivities='").append(com.sforce.ws.util.Verbose.toString(OpenActivities)).append("'\n");
      sb.append(" OrderItems='").append(com.sforce.ws.util.Verbose.toString(OrderItems)).append("'\n");
      sb.append(" OrderNumber='").append(com.sforce.ws.util.Verbose.toString(OrderNumber)).append("'\n");
      sb.append(" OrderReferenceNumber='").append(com.sforce.ws.util.Verbose.toString(OrderReferenceNumber)).append("'\n");
      sb.append(" Orders='").append(com.sforce.ws.util.Verbose.toString(Orders)).append("'\n");
      sb.append(" OriginalOrder='").append(com.sforce.ws.util.Verbose.toString(OriginalOrder)).append("'\n");
      sb.append(" OriginalOrderId='").append(com.sforce.ws.util.Verbose.toString(OriginalOrderId)).append("'\n");
      sb.append(" Owner='").append(com.sforce.ws.util.Verbose.toString(Owner)).append("'\n");
      sb.append(" OwnerId='").append(com.sforce.ws.util.Verbose.toString(OwnerId)).append("'\n");
      sb.append(" PoDate='").append(com.sforce.ws.util.Verbose.toString(PoDate)).append("'\n");
      sb.append(" PoNumber='").append(com.sforce.ws.util.Verbose.toString(PoNumber)).append("'\n");
      sb.append(" Pricebook2='").append(com.sforce.ws.util.Verbose.toString(Pricebook2)).append("'\n");
      sb.append(" Pricebook2Id='").append(com.sforce.ws.util.Verbose.toString(Pricebook2Id)).append("'\n");
      sb.append(" ProcessInstances='").append(com.sforce.ws.util.Verbose.toString(ProcessInstances)).append("'\n");
      sb.append(" ProcessSteps='").append(com.sforce.ws.util.Verbose.toString(ProcessSteps)).append("'\n");
      sb.append(" ShipToContact='").append(com.sforce.ws.util.Verbose.toString(ShipToContact)).append("'\n");
      sb.append(" ShipToContactId='").append(com.sforce.ws.util.Verbose.toString(ShipToContactId)).append("'\n");
      sb.append(" ShippingAddress='").append(com.sforce.ws.util.Verbose.toString(ShippingAddress)).append("'\n");
      sb.append(" ShippingCity='").append(com.sforce.ws.util.Verbose.toString(ShippingCity)).append("'\n");
      sb.append(" ShippingCountry='").append(com.sforce.ws.util.Verbose.toString(ShippingCountry)).append("'\n");
      sb.append(" ShippingLatitude='").append(com.sforce.ws.util.Verbose.toString(ShippingLatitude)).append("'\n");
      sb.append(" ShippingLongitude='").append(com.sforce.ws.util.Verbose.toString(ShippingLongitude)).append("'\n");
      sb.append(" ShippingPostalCode='").append(com.sforce.ws.util.Verbose.toString(ShippingPostalCode)).append("'\n");
      sb.append(" ShippingState='").append(com.sforce.ws.util.Verbose.toString(ShippingState)).append("'\n");
      sb.append(" ShippingStreet='").append(com.sforce.ws.util.Verbose.toString(ShippingStreet)).append("'\n");
      sb.append(" Status='").append(com.sforce.ws.util.Verbose.toString(Status)).append("'\n");
      sb.append(" StatusCode='").append(com.sforce.ws.util.Verbose.toString(StatusCode)).append("'\n");
      sb.append(" SystemModstamp='").append(com.sforce.ws.util.Verbose.toString(SystemModstamp)).append("'\n");
      sb.append(" Tasks='").append(com.sforce.ws.util.Verbose.toString(Tasks)).append("'\n");
      sb.append(" TopicAssignments='").append(com.sforce.ws.util.Verbose.toString(TopicAssignments)).append("'\n");
      sb.append(" TotalAmount='").append(com.sforce.ws.util.Verbose.toString(TotalAmount)).append("'\n");
      sb.append(" Type='").append(com.sforce.ws.util.Verbose.toString(Type)).append("'\n");
      sb.append(" UserRecordAccess='").append(com.sforce.ws.util.Verbose.toString(UserRecordAccess)).append("'\n");
      sb.append("]\n");
      return sb.toString();
    }

}
