package com.onenow.main;

import java.util.logging.Level;

import com.amazonaws.services.kinesis.clientlibrary.interfaces.IRecordProcessorFactory;
import com.amazonaws.services.kinesis.clientlibrary.lib.worker.InitialPositionInStream;
import com.onenow.constant.StreamName;
import com.onenow.constant.DataType;
import com.onenow.data.EventActivity;
import com.onenow.data.EventActivityGenericStreaming;
import com.onenow.data.EventActivityGreekStreaming;
import com.onenow.data.EventActivityPriceHistory;
import com.onenow.data.EventActivityPriceSizeRealtime;
import com.onenow.data.EventActivityPriceStreaming;
import com.onenow.data.EventActivitySizeStreaming;
import com.onenow.data.EventActivityVolatilityStreaming;
import com.onenow.io.BusProcessingFactory;
import com.onenow.io.BusSystem;
import com.onenow.io.DBTimeSeriesGeneric;
import com.onenow.io.DBTimeSeriesGreek;
import com.onenow.io.DBTimeSeriesPrice;
import com.onenow.io.DBTimeSeriesSize;
import com.onenow.io.DBTimeSeriesVolatility;
import com.onenow.util.InitLogger;
import com.onenow.util.TimeParser;
import com.onenow.util.Watchr;

public class ClerkMain {

	/**
	 * Processes real-time data
	 * Data is generated by InvestorMain itself, and also by requests to it from HistorianRTMain
	 * @param args
	 */
	public static void main(String[] args) {

		InitLogger.run("");

		TimeParser.sleep(180); // boot sequence

		BusSystem.readAllStreams(InitialPositionInStream.LATEST);

	}
}
