package com.onenow.constant;

public enum ColumnName {

	TIME, PRICE, SIZE,
	SOURCE, TIMING, TRADETYPE, UNDERLYING, INVTYPE, OPTIONSTRIKE, OPTIONEXP, FUTUREEXP,
	IMPVOLATILITY, DELTA, GAMMA, VEGA, THETA
}
