package com.onenow.constant;

public enum DBQuery {
	SELECT, FROM, GROUP, BY, WHERE, AND,
	TIME, PRICE, 
	FIRST, LAST, DIFFERENCE, MIN, MAX, MEAN, MODE, MEDIAN, STDDEV, DISTINCT, COUNT, SUM, DERIVATIVE
	
}
