package com.onenow.constant;

public enum QueueName {

	HISTORY_DEVELOPMENT, HISTORY_STAGING, HISTORY_PRODUCTION,
	REALTIME_DEVELOPMENT, REALTIME_STAGING, REALTIME_PRODUCTION,
	ANALYST_DEVELOPMENT, ANALYST_STAGING, ANALYST_PRODUCTION

}
