package com.onenow.constant;

public enum SamplingRate {
	UHFREQ, HIFREQ, SCALP, SWING, TREND,
	UHFSHORT, UHFMEDIUM, UHFLONG,
	HFSHORT, HFMEDIUM, HFLONG,
	SCALPSHORT, SCALPMEDIUM, SCALPLONG, 
	SWINGSHORT, SWINGMEDIUM, SWINGLONG, 
	TRENDSHORT, TRENDMEDIUM, TRENDLONG
}
