package com.onenow.constant;

public enum SizeType {
	BID_SIZE, ASK_SIZE, TRADED_SIZE,
	
	VOLUME, AVG_VOLUME, VOLUME_RATE, 
	OPTION_CALL_OPEN_INTEREST, OPTION_PUT_OPEN_INTEREST,
	OPTION_CALL_VOLUME, OPTION_PUT_VOLUME,
	REGULATORY_IMBALANCE, AUCTION_VOLUME, AUCTION_IMBALANCE
	
	
	// FROZEN, MARKETDEPTH,
}
