package com.onenow.constant;

public enum StreamingData {

	PRICE_HISTORY, GREEK_HISTORY,
	PRICESIZE_REALTIME, 
	PRICE_STREAMING, SIZE_STREAMING, GREEK_STREAMING, VOLATILITY_STREAMING, GENERIC_STREAMING,
	
}
