package com.onenow.constant;

public enum StreamName {
	
	PRICE_HISTORY_STAGING, GREEK_HISTORY_STAGING,
	PRICESIZE_REALTIME_STAGING,
	PRICE_STREAMING_STAGING, SIZE_STREAMING_STAGING,
	GREEK_STREAMING_STAGING, VOLATILITY_STREAMING_STAGING, GENERIC_STREAMING_STAGING,
		
}
