package com.onenow.constant;

public enum StreamName {
	PRIMARY_STAGING, PRIMARY_PRODUCTION, PRIMARY_DEVELOPMENT,
	STANDBY_STAGING, STANDBY_PRODUCTION, STANDBY_DEVELOPMENT, 
	HISTORY_STAGING, HISTORY_PRODUCTION, HISTORY_DEVELOPMENT, 
	REALTIME_STAGING, REALTIME_PRODUCTION, REALTIME_DEVELOPMENT, 
	STREAMING_STAGING, STREAMING_PRODUCTION, STREAMING_DEVELOPMENT
}
