package com.onenow.constant;

public enum VolatilityType {
	// implied
	OPTION_IMPLIED_VOL,
	MODEL_OPTION, MODEL_OPTION_COMPUTATION, 
	CUST_OPTION_COMPUTATION, 
	ASK_OPTION_COMPUTATION, BID_OPTION_COMPUTATION, LAST_OPTION_COMPUTATION,
	// historical
	RT_HISTORICAL_VOL, OPTION_HISTORICAL_VOL
}
